### ISSUE TITLE
Prometheus: Rollup not reset after each dump interval ?

### ISSUE THREAD

**Issue by nfranchet** [kentik/ktranslate#107]
This is the command i use 
`command: "-format prometheus -kentik_email noc@acorus.net -format_rollup prometheus -sinks prometheus -prom_listen=:8084 -rollup_interval 60 -rollups s_sum,in_bytes,in_bytes,device_name,src_as,dst_as,protocol,application,src_geo,dst_geo,input_port -rollups s_sum,in_pkts,in_pkts,device_name,src_as,dst_as,protocol,application,src_geo,dst_geo,input_port"`

And instead of the traffic at each point, I have the sum of traffic starting from ktranslate launch.

**Comment by i3149** [comment]
Can you use the `rate()` function to calculate traffic over time? That's how we seem most people query this data.
