### ISSUE TITLE
rollups argument description in --help should include rollup name

### ISSUE THREAD

**Issue by dpajin-kentik** [kentik/ktranslate#11]
I have tested ktranslate:v2 and rollups and what works for me is the syntax in form of the `type, name, metric, dimension1, dimension2, ...`. 
What is clear is that at the second place it has to be some kind of "rollup name" and not the metric. 

For example, if I use the following argument: 
```
-rollups sum,src_addr_grouping,in_bytes,src_addr,protocol
```
the JSON output will be the following:
```
{ 
  "dimension": "89.21.210.85|UDP", 
  "metric": 2919044, 
  "eventType": "KFlow:in_bytes:src_addr:protocol", 
  "keyJoin": "|", 
  "interval": 31294705227, 
  "Name": "src_addr_grouping", 
  "Count": 3, 
  "Min": 700948, 
  "Max": 1141656, 
  "Provider": "kentik-router" 
}, 
```

From `ktranslate --help`, this is wrong:
```  
-rollups value
    	Any rollups to use. Format: type, metric, dimension 1, dimension 2, ..., dimension n: sum,in_bytes,dst_addr
```

some parts of our KB documentation are wrong:
- this is correct: https://kb.kentik.com/v0/Fc19.htm#Fc19-ktranslate_Operations
- This is wrong in the table: https://kb.kentik.com/v0/Fc19.htm#Fc19-ktranslate_CLI_Reference
- Example is wrong: https://kb.kentik.com/v0/Fc19.htm#Fc19-ktranslate_Operation_Examples

**Comment by i3149** [comment]
Updated the -h flag. @pdelancie  -- can you update the KB entries?

**Comment by dpajin-kentik** [comment]
Yes, I see the update in the ktranslate lastest container

**Comment by pdelancie** [comment]
Sure. I assume that you are referring to the table in the topic *ktranslate
CLI Reference* (
https://kb.kentik.com/v0/Fc19.htm#Fc19-ktranslate_CLI_Reference), and that
the row that should change is this:
-rollups (value) Any rollups to use. Structure: method, metric, dimensions
(1 through n). Available methods are sum, min, max, mean, median, entropy,
percentilerank, percentile, unique.
*Note:* For available metrics see *ktranslate Metrics and Dimensions*
<https://kb.kentik.com/v0/Fc19.htm#Fc19-ktranslate_Metrics_and_Dimensions>.

But can you please be more specific as to what the description should
change to (I don't have a way to run ktranslate and see what returns from
-h)?

thx,
Philip De Lancie
Senior Writer, Technical & Marketing
Kentik Technologies

**Comment by dpajin-kentik** [comment]
Hi @pdelancie, this is currently in --help:
```
  -rollups value
    	Any rollups to use. Format: type, name, metric, dimension 1, dimension 2, ..., dimension n: sum,bytes,in_bytes,dst_addr

```
structure is method, **name**, metric, dimensions

**Comment by pdelancie** [comment]
ok, thx

Philip De Lancie
Senior Writer, Technical & Marketing
Kentik Technologies

**Comment by pdelancie** [comment]
So based on the change that's called out the revised table row would be:

-rollups (value) Any rollups to use. Structure: method, name, metric,
dimensions (1 through n). Available methods are sum, min, max, mean,
median, entropy, percentilerank, percentile, unique.
*Note:* For available metrics see *ktranslate Metrics and Dimensions*
<https://kb.kentik.com/v0/Fc19.htm#Fc19-ktranslate_Metrics_and_Dimensions>.

But I also note that the the existing entry says "Available methods are
sum, min, max, mean, median, entropy, percentilerank, percentile, unique."
while the new version says "sum,bytes,in_bytes,dst_addr"
Are those supposed to replace the list of "available methods"?

Philip De Lancie
Senior Writer, Technical & Marketing
Kentik Technologies

**Comment by dpajin-kentik** [comment]
> But I also note that the the existing entry says "Available methods are
sum, min, max, mean, median, entropy, percentilerank, percentile, unique."
while the new version says "sum,bytes,in_bytes,dst_addr"
Are those supposed to replace the list of "available methods"?

No, "sum,bytes,in_bytes,dst_addr" is just the example. In this case "method" is "sum", the "name" which is completely user configurable is "bytes" (not really good choice for example :), than "in_bytes" is the metric that wlll be "sum"ed and, "dst_addr" is one "dimension" over which the sumarization will be done.

**Comment by pdelancie** [comment]
Predictably, I'm inclined to suggest that examples be labeled as such.

thx,
Philip De Lancie
Senior Writer, Technical & Marketing
Kentik Technologies

**Comment by dpajin-kentik** [comment]
Closing thanks
