### ISSUE TITLE
FR: Randomize -metalisten port to allow for multiple containers on the same host

### ISSUE THREAD

**Issue by nr-jbiggley** [kentik/ktranslate#115]
When an existing ktranslate container is running, launching a discovery results in an error

`Error running meta server: listen tcp 0.0.0.0:8083: bind: address already in use`

Suggest that when **-snmp_discovery=true** that **-metalisten** run on a randomized port. This will also facilitate scheduled discoveries without having to manage running ktranslate instances.

**Comment by i3149** [comment]
Somewhat of a chicken and egg problem. You can get this random binding behavior by setting the flag `--metalisten=""`. I think makes sense to default this when disco is used, will update.
