### ISSUE TITLE
Randomize metalisten port for non-discovery containers too

### ISSUE THREAD

**Issue by nr-jbiggley** [kentik/ktranslate#118]
As reported [here](https://github.com/newrelic/docs-website/issues/3701#issuecomment-908397300), multiple containers on the same host causes a collision on port 8083.

Is there a risk to setting _metalisten=""_ to randomize the port for non-discovery (SNMP and flow) containers too?

**Comment by i3149** [comment]
Decided to just remove the metalisten flag entirely. Users can explicitly set it if they need it, but otherwise, its not set.
