### ISSUE TITLE
-snmp_walk_oid flag is not supported in the latest image (v2)

### ISSUE THREAD

**Issue by nr-jbiggley** [kentik/ktranslate#119]
Running container for an SNMP discovery as written results in an error. Forcing image to kentik/ktranslate:latest works

If `latest` is the preferred route, docs and wiki should be updated

```
docker run -ti --name ktranslate-discovery --rm --net=host \
  -v `pwd`/snmp-base.yaml:/snmp-base.yaml \
  kentik/ktranslate:v2 \
    -snmp /snmp-base.yaml \
    -log_level info \
    -snmp_do_walk my_device \
    -snmp_walk_oid .1.3.6.1 
```

**Comment by i3149** [comment]
You likely forgot to pull the most recent `v2` image? Docker doesn't automatically do this each run, which is both a pro and con.
