### ISSUE TITLE
SNMPv3 fails when using AES256

### ISSUE THREAD

**Issue by nr-jbiggley** [kentik/ktranslate#129]
Tried to deploy SNMPv3 using AES256 and it didn't like it. Had to drop back to using AES128.

@i3149 as per our Slack chat

**Comment by i3149** [comment]
Can you ask they to try `AES256C`. This is Reeder-AES256 vs Blumenthal-AES256, might make a difference? 

Else, #130 pulls in a lot of bug fixes around v3. Once this is merged, worth while trying again without changing the config.

**Comment by nr-jbiggley** [comment]
As per troubleshooting convo, FR to support ISO-8859-1 (minimum) and preferably UTF8 for complex character sets.

**Comment by nr-jbiggley** [comment]
As per customer and PR 130, this issue is resolved.
