### ISSUE TITLE
missing or wrong info in JSON kflow represenation

### ISSUE THREAD

**Issue by dpajin-kentik** [kentik/ktranslate#13]
Below is the JSON format of Kflows that are received from Kentik.

- Field `device_name` is empty
- There are no fields for the following enrichment information:
  - Port name (port = device interface)
  - Port description 
  - Port connectivity type 
  - Port network boundary 
- Some integer value is shown instead of route prefix: 
  - Src_route_prefix 
  - Dst_route_prefix 

```
{ 
"timestamp": 1624824853, 
"dst_as": 65500, 
"dst_geo": "DE", 
"header_len": 0, 
"in_bytes": 44, 
"in_pkts": 1, 
"input_port": 551, 
"ip_size": 0, 
"dst_addr": "193.177.129.11", 
"src_addr": "104.43.218.215", 
"l4_dst_port": 0, 
"l4_src_port": 2048, 
"output_port": 549, 
"protocol": "ICMP", 
"sampled_packet_size": 44, 
"src_as": 8075, 
"src_geo": "US", 
"tcp_flags": 0, 
"tos": 0, 
"vlan_in": 0, 
"vlan_out": 0, 
"next_hop": "", 
"mpls_type": 0, 
"out_bytes": 0, 
"out_pkts": 0, 
"tcp_rx": 0, 
"src_flow_tags": "", 
"dst_flow_tags": "", 
"sample_rate": 32, 
"device_id": 1171, 
"device_name": "", 
"company_id": 1013, 
"dst_bgp_as_path": "", 
"dst_bgp_comm": "", 
"src_bpg_as_path": "", 
"src_bgp_comm": "", 
"src_nexthop_as": 174, 
"dst_nexthop_as": 65500, 
"src_geo_region": "Iowa", 
"dst_geo_region": "-", 
"src_geo_city": "Des Moines", 
"dst_geo_city": "-", 
"dst_nexthop": "193.177.128.9", 
"src_nexthop": "149.29.8.217", 
"src_route_prefix": 1747451904, 
"dst_route_prefix": 3249635595, 
"src_second_asn": 8075, 
"dst_second_asn": 0, 
"src_third_asn": 0, 
"dst_third_asn": 0, 
"src_eth_mac": "00:00:00:00:00:00:00:00", 
"dst_eth_mac": "00:00:00:00:00:00:00:00", 
"input_int_desc": "", 
"output_int_desc": "", 
"input_int_alias": "", 
"output_int_alias": "", 
"input_int_capacity": 0, 
"output_int_capacity": 0, 
"input_int_ip": "", 
"output_int_ip": "", 
"custom_str": { 
"1036": "", 
"1037": "AzureCloud.centralus", 
"src_as_name": "MICROSOFT-CORP-MSN-AS-BLOCK", 
"dst_as_name": "-Private", 
"1435": "inbound", 
"395": "ICMP", 
"1035": "azure", 
"1038": "" 
}, 

custom_bigint": { 
"129": 0, 
"130": 0 
}, 
"eventType": "KFlow", 
"provider": "kentik-router" 
}, 
 
```

**Comment by i3149** [comment]
Good call out on Route Prefixes. Should be fixed in https://github.com/kentik/ktranslate/pull/52

Re device_name, Port name (port = device interface), Port description, Port connectivity type, Port network boundary these all get matched at query time not ingest time so aren't available in the firehose.

**Comment by dpajin-kentik** [comment]
route prefixes do not have length, however I think this should be included:

```
        "src_route_prefix": "105.16.0.0",
        "dst_route_prefix": "193.177.129.27",
```

I posted the question on the slack channel about connectivity type and network boundary as from what I can see in portal UI, it seems like these are written in DB. I see that @kagawaa confirmed this is the case, so I guess these info can be included. 

It might be worth if you can also include "device IP" address as I think that should be more useful than "device_id". 

I understand that there is a technical limitation and that you probably try to make this efficient, so that you don't enrich everything, but if I put customer's hat, I would expect to have these info as well
