### ISSUE TITLE
Make the discovery process more puppet friendly. 

### ISSUE THREAD

**Issue by daveseff** [kentik/ktranslate#135]
You say to edit snmp-base.yaml, which we construct using a puppet template. The discovery process then overwrites that file when it runs, so puppet is confused when it maintains the snmp-base.yaml file. It would be nicer to have an output yaml file that the discovery process then writes to be used by the ktranslate container and the base yaml left alone. If this is currently possible then the documentation should give this as an option.

**Comment by i3149** [comment]
Good point here. Would a flag like `--snmp-out-file` which defaults to the value of `--snmp` work for your setup? Another approach would be a `discovery_output` setting in the yaml file itself like: 

```
discovery:
  cidrs:
    - ...
  debug: false
  ports:
  - 161
  default_communities:
  - public
  default_v3: null
  add_devices: true
  threads: 4
  use_snmp_v1: false
  replace_devices: false
  discovery_output: "@discovery-results.yaml"
```

Or split the difference like a helm chart and allow both?

**Comment by daveseff** [comment]
Having an ```--snmp-out-file``` would be a huge step. As long as the 'starter' yaml file can remain untouched by the discovery process then puppet can maintain and trigger a new discovery run when my network admins want to update their cidrs.

**Comment by i3149** [comment]
Cool. I'll add `--snmp-out-file` as a new flag.

**Comment by i3149** [comment]
Latest build should support something like this: 

```
docker run -ti --name ktranslate-discovery --rm --net=host \
  --user `id -u`:`id -g` \
  -v `pwd`/snmp-base.yaml:/snmp-base.yaml \
  -v `pwd`/dir:/dir \
  kentik/ktranslate:v2 \
    -snmp /snmp-base.yaml \
    -log_level info \
    -snmp_out_file=/dir/snmp-out.yaml \
    -snmp_discovery=true
```

Where dir is a directory you create to hold the output of  `--snmp_out_file`

Note I moved to underscore from dash to keep consistent with the other flags.

**Comment by i3149** [comment]
Let me know if the latest build works for you and I'll close.

**Comment by daveseff** [comment]
Thanks for the quick response. I'll have a test shortly.

**Comment by daveseff** [comment]
I had to add volumes for both yaml files:
```-v /root/snmp-starter.yaml:/snmp-starter.yaml -v /root/snmp-base.yaml:/snmp-base.yaml```
This wasn't a big deal. I added ```-snmp_out_file /snmp-base.yaml``` and ran discovery. It seems to work as expected. Thanks.
