### ISSUE TITLE
[Bug] match_attributes filter is not working 

### ISSUE THREAD

**Issue by araddas** [kentik/ktranslate#162]
match_attributes is not working for the following filter, per https://play.golang.org/p/p-4mLKnChmS this filter should be excluding these metrics. AFAIK this pull request should have allowed this to work https://github.com/kentik/ktranslate/pull/134

```
match_attributes:
   entity_name: Sensor
```

<img width="1468" alt="Screen Shot 2021-10-21 at 1 45 21 PM" src="https://user-images.githubusercontent.com/24640633/138355452-ec2e74a9-2056-4220-a5a8-696bd3c27a6f.png">

**Comment by i3149** [comment]
@araddas can you pull the latest image and test now? Thanks.

**Comment by araddas** [comment]
> @araddas can you pull the latest image and test now? Thanks.

This is dropping all entity_name key/values now, the inverse of what I would have expected

**Confirming Image ID**
```
# docker images
REPOSITORY          TAG       IMAGE ID       CREATED       SIZE
kentik/ktranslate   v2        767cbcd13bbb   2 hours ago   142MB
```


**Current Match Attribute Config**
```
match_attributes:
    if_Alias: ^\*M
    entity_name: Sensor|[T-t]emp
```

**Missing entity_name attribute**
![missing_attrib](https://user-images.githubusercontent.com/24640633/139756824-5a3711e5-4d93-487a-a7df-2afb15bce6d2.png)

**Comment by i3149** [comment]
`entity_name` is only valid for the `cswSwitchInfoTable` table: 
https://github.com/kentik/snmp-profiles/blob/main/profiles/kentik_snmp/cisco/cisco-all-devices.yml#L293

These was a separate bug which incorrectly applying this attribute to the entSensorValueTable. So it not being present is expected now. 

Are you enabling the `CISCO-STACKWISE-MIB`? If so, do you have the metric `kentik.snmp.cswSwitchState`? This should have `entity_name` as an attribute.

**Comment by araddas** [comment]
@i3149 the stackwise mib is discovered and it worked prior to this image. I don't believe removing the entity_name is the correct thing to do, the entPhysicalDescr provides the human readable name for all of the physical devices attached to the switch (PSU, Temp Sensors, TX/RX Sensor, Etc). By removing the mapping of entity_name to the entSensorValue, you've removed the context. An example of this can be found below. You have to derive the entity name from the ENTITY-MIB and then use the index id to map that to the CISCO-ENTITY-SENSOR-MIB. 
```
SNMPv2-SMI::mib-2.47.1.1.1.1.2.5073_=_STRING:_"Te5/0/1_Module_Temperature_Sensor"
SNMPv2-SMI::enterprises.9.9.91.1.1.1.1.4.5073 = INTEGER: 33
SNMPv2-SMI::mib-2.47.1.1.1.1.2.5074_=_STRING:_"Te5/0/1_Supply_Voltage_Sensor"
SNMPv2-SMI::enterprises.9.9.91.1.1.1.1.4.5074 = INTEGER: 3
SNMPv2-SMI::mib-2.47.1.1.1.1.2.5075_=_STRING:_"Te5/0/1_Bias_Current_Sensor"
SNMPv2-SMI::enterprises.9.9.91.1.1.1.1.4.5075 = INTEGER: 7
SNMPv2-SMI::mib-2.47.1.1.1.1.2.5076_=_STRING:_"Te5/0/1_Transmit_Power_Sensor"
SNMPv2-SMI::enterprises.9.9.91.1.1.1.1.4.5076 = INTEGER: -2
SNMPv2-SMI::mib-2.47.1.1.1.1.2.5077_=_STRING:_"Te5/0/1_Receive_Power_Sensor"
SNMPv2-SMI::enterprises.9.9.91.1.1.1.1.4.5077 = INTEGER: -2
SNMPv2-SMI::mib-2.47.1.1.1.1.2.5079_=_STRING:_"Te5/0/2_Module_Temperature_Sensor"
SNMPv2-SMI::enterprises.9.9.91.1.1.1.1.4.5079 = INTEGER: 34
SNMPv2-SMI::mib-2.47.1.1.1.1.2.5080_=_STRING:_"Te5/0/2_Supply_Voltage_Sensor"
SNMPv2-SMI::enterprises.9.9.91.1.1.1.1.4.5080 = INTEGER: 3
SNMPv2-SMI::mib-2.47.1.1.1.1.2.5081_=_STRING:_"Te5/0/2_Bias_Current_Sensor"
SNMPv2-SMI::enterprises.9.9.91.1.1.1.1.4.5081 = INTEGER: 0
SNMPv2-SMI::mib-2.47.1.1.1.1.2.5082_=_STRING:_"Te5/0/2_Transmit_Power_Sensor"
SNMPv2-SMI::enterprises.9.9.91.1.1.1.1.4.5082 = INTEGER: -40
SNMPv2-SMI::mib-2.47.1.1.1.1.2.5083_=_STRING:_"Te5/0/2_Receive_Power_Sensor"
SNMPv2-SMI::enterprises.9.9.91.1.1.1.1.4.5083 = INTEGER: -2
SNMPv2-SMI::mib-2.47.1.1.1.1.2.6073_=_STRING:_"Te6/0/1_Module_Temperature_Sensor"
SNMPv2-SMI::enterprises.9.9.91.1.1.1.1.4.6073 = INTEGER: 31
SNMPv2-SMI::mib-2.47.1.1.1.1.2.6074_=_STRING:_"Te6/0/1_Supply_Voltage_Sensor"
SNMPv2-SMI::enterprises.9.9.91.1.1.1.1.4.6074 = INTEGER: 3
SNMPv2-SMI::mib-2.47.1.1.1.1.2.6075_=_STRING:_"Te6/0/1_Bias_Current_Sensor"
SNMPv2-SMI::enterprises.9.9.91.1.1.1.1.4.6075 = INTEGER: 8
SNMPv2-SMI::mib-2.47.1.1.1.1.2.6076_=_STRING:_"Te6/0/1_Transmit_Power_Sensor"
SNMPv2-SMI::enterprises.9.9.91.1.1.1.1.4.6076 = INTEGER: -2
SNMPv2-SMI::mib-2.47.1.1.1.1.2.6077_=_STRING:_"Te6/0/1_Receive_Power_Sensor"
SNMPv2-SMI::enterprises.9.9.91.1.1.1.1.4.6077 = INTEGER: -1
```

**Comment by i3149** [comment]
That makes sense. We'll work to get a revised set of profiles out soon.
