### ISSUE TITLE
FR: Additional decoration for container log forwarder

### ISSUE THREAD

**Issue by Mesverrum** [kentik/ktranslate#168]
As a customer with multiple ktranslate containers we have to write parsing rules in NR to be able to easily filter/facet on the container name.  For a better OOTB user experience it would be helpful to decorate the log tee records with additional information as separate attributes such as

{
"collector.name":"ktranslate"
"instrumentation.provider":"kentik"
"hostname":"kentik"
"container_id":"fajfn13245lkm"
"container_name":"kentik-snmp-routers"
"message":"2021-10-25T18:04:40.734 ktranslate/snmp [Info] KTranslate>isp-gw Adding device metric .1.3.6.1.2.1.6.6.0 -> tcpPassiveOpens"
}

This will probably also apply to syslog forwarding.

**Comment by i3149** [comment]
I would look at using `-service_name` flag to differentiate. Getting these container information from inside docker is non-trivial from what I can see.  service_name defaults to ktranslate but can be set to anything. for example, `-service_name=kentik-snmp-routers` To get roughly the same idea.
