### ISSUE TITLE
Bug: Engine ID for dedupe isn't working correctly for HPE switches

### ISSUE THREAD

**Issue by Mesverrum** [kentik/ktranslate#188]
Customer was discovering 13 HPE switches and 11 of them got deduped away.  

![image](https://user-images.githubusercontent.com/17046211/141493729-53b05a78-c331-4adf-82c1-2823099b9623.png)

I'm working to get the logs from the discovery sent over now

**Comment by i3149** [comment]
Its really hard to tell but I'm pretty sure these are legit dedups based on a shared engine ID. To turn this behavior off, set `no_dedup_engine_id: true` in the snmp.yaml disco section. I was gonna put a snarky link to the wiki here but I realized I forgot to document this feature.

**Comment by i3149** [comment]
Added now: https://github.com/kentik/ktranslate/wiki/Sample-SNMP-config

**Comment by Mesverrum** [comment]
the customer is pretty insistent that these are 13 distinct devices which calls into question our engine id calculation?

**Comment by i3149** [comment]
OK -- I'm pretty sure I know what's going on. We're parsing enigine_id as a mac address:

https://github.com/kentik/ktranslate/blob/main/pkg/inputs/snmp/metadata/device_metadata.go#L110

But this is of fixed size. Likely the engineIDs are different, but at a byte offset which is off the end of what we parse. Will look at making this consume the whole byte string.

**Comment by i3149** [comment]
OK -- I committed a possible fix. Can you ask customer to pull latest image and try again -- thanks!

**Comment by Mesverrum** [comment]
I let the account team know, I'll update when I hear back
