### ISSUE TITLE
Feature Request: Option to enable DNS lookup for IP's

### ISSUE THREAD

**Issue by Mesverrum** [kentik/ktranslate#197]
As a customer seeing flows entities only by IP address can be confusing.  Can we offer an option to enable DNS lookups for observed IP addresses and decorate that to the records.

**Comment by i3149** [comment]
This exists! 

Use the flag:

```
-dns string
    	Resolve IPs at this ip:port
```

It will do a best effort job of doing a reverse dns resolve for all ips seen here. Requires both ip and port (8.8.8.8:53) for example.

**Comment by Mesverrum** [comment]
excellent, i'll give it a go
