### ISSUE TITLE
SNMP Provider match isn't working as expected

### ISSUE THREAD

**Issue by thezackm** [kentik/ktranslate#2]
looking at [load.go](https://github.com/kentik/ktranslate/blob/86776214d0b227eba1c578495b839666422289fe/pkg/inputs/snmp/mibs/load.go#L175-L205), it seems we should be somewhat gracefully matching the provider value based on some known attributes on discovered devices. 

On the current version, all discovered devices are being matched as `kentik-router`, even if they have matching logic for other providers. Case in point, we have a discovery that came back with 4 devices using `mib_profile: cisco-catalyst.yml`; which I think should have matched below, but it seems to have missed. 

```go
if strings.Contains(combo, "switch") || strings.Contains(profile, "cisco-catalyst") {
		return kt.ProviderSwitch, true
	}
```

**Comment by i3149** [comment]
Should be fixed with https://github.com/kentik/ktranslate/pull/4/commits/1953df7d5f812bfbaf928f52750950bcae5842b8
