### ISSUE TITLE
SNMP collection: ifOperStatus and ifAdminStatus wrong values

### ISSUE THREAD

**Issue by dpajin-kentik** [kentik/ktranslate#20]
below is the example of the values received when running ktranslate as SNMP collector:
The values of `ifOperStatus` and `ifAdminStatus` are always 0, although the value should be 1 or 2 or possibly some other value.
I also notice that other OID values are not the exact as what I get from snmpwalk, so I concluded that since you have uptime, you are treating all OIDs as counters and supply only the difference (increase) from the previously collected value. 

I guess that the case with `ifOperStatus` and `ifAdminStatus`, since those values are not changing, they are always 0. 
Obviously your definition of IF-MIB in snmp profiles YAML files is missing the value type. Not all the OID are counters, some values are gauge, some values are timeticks and so on... this should be also configurable in YAML files.

```
        "custom_bigint": {
            "ifInErrors": 0,
            "ifInDiscards": 0,
            "ifHCOutMulticastPkts": 0,
            "Uptime": 6006,
            "ifHCInMulticastPkts": 0,
            "ifAdminStatus": 0,
            "ifOutErrors": 0,
            "ifHCInUcastPkts": 324,
            "ifOperStatus": 0,
            "ifHCInBroadcastPkts": 0,
            "ifHCOutOctets": 89290,
            "ifOutDiscards": 0,
            "ifHCOutUcastPkts": 324,
            "ifHCOutBroadcastPkts": 0,
            "ifHCInOctets": 69833
        },
        "eventType": "KSnmpInterfaceMetric",
        "provider": "kentik-router"
    },
```

In IP-MIB yaml I see there is some kind of mapping between values and strings, but this is only in IP-MIB and under the section metric tags. I have tried to do similar for `symbols` in `if-mib.yml` (see below), but so I guess it is not implementable on values. 
It might be good to have such an option for values, there are other OIDs which have mapping between integer values and the meaning, for example `bgpPeerState`.
```
  - OID: 1.3.6.1.2.1.2.2.1.7
    name: ifAdminStatus
    mapping:
      1: up
      2: down
  - OID: 1.3.6.1.2.1.2.2.1.8
    name: ifOperStatus
    mapping:
      1: up
      2: down
```

**Comment by i3149** [comment]
Json is a bad format for snmp. Try running with `-format=new_relic_metric`

./bin/ktranslate -snmp snmp.yaml -format new_relic_metric -log_level info

You should get results like this, with the correct ifOperStatus and ifAdminStatus values.
```
      {
        "name": "kentik.snmp.ifHCInBroadcastPkts",
        "type": "gauge",
        "value": 0,
        "attributes": {
          "objectIdentifier": ".1.3.6.1.2.1.31.1.1.1.9",
          "device_name": "bart",
          "eventType": "KSnmpInterfaceMetric",
          "if_Address": "127.0.0.1",
          "if_ifMtu": "16384",
          "DropMetric": false,
          "Uptime": 2999,
          "SysName": "bart.folsom",
          "if_ifLastChange": "0",
          "input_port": 6,
          "output_port": 6,
          "if_ifAdminStatus": "1",
          "instrumentation.name": "snmp",
          "if_Netmask": "255.0.0.0",
          "SysObjectID": ".1.3.6.1.4.1.8072.3.2.8",
          "if_Index": "6",
          "SysDescr": "FreeBSD bart.folsom 12.1-RELEASE-p18-HBSD FreeBSD 12.1-RELEASE-p18-HBSD #1  815defa6fd0(stable/21.1)-dirty: Mon Jun 14 09:17:18 CEST 2021     root@sensey:/usr/obj/usr/src/amd64.amd64/sys/SMP amd64",
          "if_Description": "lo0",
          "if_ifConnectorPresent": "physical",
          "provider": "kentik-router",
          "if_ifOperStatus": "1",
          "src_addr": "10.10.0.1",
          "SysServices": 0,
          "if_Speed": 0
        }
```

You can also map these enums to values like you were suggesting with https://github.com/kentik/ktranslate/blob/main/config/profiles/kentik_snmp/_general/if-mib.yml#L33

**Comment by i3149** [comment]
Should be good now, both in the json format and new_relic_metric.

**Comment by dpajin-kentik** [comment]
tested, it works:

```
        "custom_str": {
            "key1": "aaaa",
            "key2": "bbbb",
            "ks_ifOperStatus": "down",
            "ks_ifAdminStatus": "up",
            "src_as_name": "Private IP"
        },
        "custom_bigint": {
            "ifHCOutUcastPkts": 0,
            "ifOutErrors": 0,
            "ifOutDiscards": 0,
            "ifHCInBroadcastPkts": 0,
            "ifAdminStatus": 1,
            "ifInDiscards": 0,
            "ifHCOutMulticastPkts": 0,
            "ifHCOutOctets": 0,
            "ifHCInOctets": 0,
            "ifHCOutBroadcastPkts": 0,
            "ifOperStatus": 2,
            "ifHCInMulticastPkts": 0,
            "ifInErrors": 0,
            "ifHCInUcastPkts": 0,
            "Uptime": 5996
        },
```
