### ISSUE TITLE
SNMP table individual metrics do not preserve defined metadata.

### ISSUE THREAD

**Issue by dgcom** [kentik/ktranslate#200]
For example, you poll a device which has this defined in configuration:
```
    user_tags: 
        env: stg
```
When you look at the data in NewRelic, this (and other metadata) is available for simple SNMP counters, for example `kentik.snmp.Uptime` 
However, any counters which are part of the SNMP table do not have this attributes, for example `kentik.snmp.ipIfStatsHCInOctets` - only carry `device_name` as usable metadata.

This creates issues when designing custom dashboards which try to filter on tags instead of individual host names.

Required behavior - any SNMP counter visible in NewRelic should have full set of metadata available.

**Comment by i3149** [comment]
What version of ktranslate are you running? This should have been fixed as of Nov 10 build.

**Comment by dgcom** [comment]
I was using image tagged latest but it was downloaded before Nov 10th.
I pulled latest image and I now see metadata sent with SNMP tables.
Although there was another breaking change - tags are now "tags.<tag_name>" instead of just "<tag_name>" good, but need to fix few custom dashboard...

**Comment by i3149** [comment]
Great. `tags.<tag_name>` is something NR asked for.
