### ISSUE TITLE
FR: Add sysDescr match for pfSense firewalls

### ISSUE THREAD

**Issue by thezackm** [kentik/ktranslate#202]
As a user, I need `ktranslate` to match both the sysOID and sysDescr to setup the correct `mib_profile` for pfSense firewalls.

Sample sysOID and sysDescr:

```
.1.3.6.1.2.1.1.1.0 = STRING: "pfSense <sysName Redacted> 21.05-RELEASE FreeBSD 12.2-STABLE amd64"
.1.3.6.1.2.1.1.2.0 = OID: .1.3.6.1.4.1.8072.3.2.8
```

**Comment by i3149** [comment]
Should be good now.
