### ISSUE TITLE
Bug: Pre-filtering of metrics not working on Memory Utilization

### ISSUE THREAD

**Issue by thezackm** [kentik/ktranslate#206]
In the [Arista Switch Profile](https://github.com/kentik/snmp-profiles/blob/c7c08fd5525607f7b75cf049f86bade6e491dbeb/profiles/kentik_snmp/arista/arista-switch.yml#L73-L96); we are polling the `HOST-RESOURCES-MIB` for `hrStorageSize` and `hrStorageUsed` (and tagging them as `MemoryTotal` and `MemoryUsed`, respectively). This is feeding `ktranslate` to calculate the `MemoryUtilization` metric automatically. 

However, we are also using the `match_attributes` key to limit polling to only table rows that match `hrStorageType: ".*25\\.2\\.1\\.2$"`; which is the `hrStorageRam` type per the spec. After pulling a new image and applying, we are seeing numerous (>5) `hrStorageTable` indexes per device, and they are all missing their metric tags for `storage_description` and `storage_type`. 

It seems that either the `match_attributes` key isn't working as expected, or the order of operations is out of sync and `ktranslate` is calculating the `MemoryUtilization` metric before processing the `metric_tags` section of the SNMP profile.

**Comment by i3149** [comment]
Because this comes in as an OID type not a string type. Fix in #204 to allow correct handing.

**Comment by i3149** [comment]
Fixed in #204
