### ISSUE TITLE
FR: Add 'logtype' attribute to logs

### ISSUE THREAD

**Issue by thezackm** [kentik/ktranslate#209]
As a user, I need logs from ktranslate to be decorated with a new field to enable New Relic to apply [built-in parsing rules](https://docs.newrelic.com/docs/logs/ui-data/parsing/#built-in-rules) on my logs that enhance my ability to search and facet on the data.

```
logtype: 'ktranslate-health'
```

**Comment by i3149** [comment]
This would not however be set on syslog logs which are forwarded from another service?

**Comment by thezackm** [comment]
correct; this would only apply to the container logs from ktranslate itself
