### ISSUE TITLE
FR: Multiplexing flow record(s) into each FlowSet for ktranslate IPFIX export 

### ISSUE THREAD

**Issue by axehayz** [kentik/ktranslate#212]
Current State:
When translating `kflow` into `ipfix` records using ktranslate, it is observed that there is always a _single flow data record_ that is encapsulated in a FlowSet. As seen in the following screengrab, every flow export packet has 10 Data FlowSets and 1 Template FlowSet; each including a single data (or template) record. The interleaving of Data and Template (and/or Options) FlowSets in a single Export packet is completely acceptable per RFC and is often encouraged.
![image](https://user-images.githubusercontent.com/12738437/145415976-e5595325-7644-4609-8c95-c17ecc7fa7c2.png)

Desired State:
Although, this works; in practice it would be ideal if multiple flow data record(s) are multiplexed in a single FlowSet. 
Something similar to [example provided here](https://datatracker.ietf.org/doc/html/draft-ietf-ipfix-protocol-00.txt#section-13).
The total number of FlowSets can still be limited (and I believe with the `max_flows_per_message` setting?)

Reasoning:
1. 1:1 correspondence in FPS generation. In our current state of operation, the total output FPS may be significantly higher than the original input FPS. This can potentially overload collector systems, or even surpass our own licensing for the same customer if they were to translate flows from one Kentik account to another. 
2. More pack in the punch....or more juice in the squeeze... or less words in the rap!?

Attached pcap for analysis.
[ktranslate-ipfix-output.pcap.zip](https://github.com/kentik/ktranslate/files/7686015/ktranslate-ipfix-output.pcap.zip)

**Comment by i3149** [comment]
Closing for now.
