### ISSUE TITLE
[Bug] if_Alias match_attribute is matching true for null/blank aliases

### ISSUE THREAD

**Issue by araddas** [kentik/ktranslate#213]
We have set a match attribute in the global config section which is working correctly for any interface that has text in the if_Alias, however, any interface that does not have text is matching  as true. In the below example we only want to monitor interfaces that begin with "[Ll]ink to" in the if_Alias which there are 32 interfaces on this specific device that fit that criteria, but you can see that kentik is picking up and monitoring 90 interfaces based on the if_Index and If_Description.

**The ifAlias and ifDescription count should match if the match_attribute is actually matching correctly.**
<img width="1679" alt="match_attribute_issue" src="https://user-images.githubusercontent.com/24640633/145465647-e85cbcd2-078d-4a16-8d60-44e33acf0780.png">

**Comment by i3149** [comment]
Closing as this is confirmed fixed.
