### ISSUE TITLE
🐛 BUG - Deduplication settings are being ignored

### ISSUE THREAD

**Issue by thezackm** [kentik/ktranslate#220]
## Synopsis:

We have observed a bug in the latest version of ktranslate when using the `discovery.no_dedup_engine_id` attribute. 

## Issue:

During SNMP discovery; the `snmp-base.yaml` file is being overwritten and the attribute is being removed from the configuration file completely. Consequently; deduplication against the engineID attribute is still occurring. This was observed across multiple executions of the SNMP discovery feature for ktranslate.

## To Recreate:

 * In the `snmp-base.yaml` file, set `discovery.no_dedup_engine_id: true`
 * Execute a discovery job for ktranslate against multiple devices with a common engineID
 * Observe the # of discovered devices against the log entries for the deduplication in the container logs
 * After discovery, check the `snmp-base.yaml` file and observe the `discovery.no_dedup_engine_id` is now missing

Sample of discovery command in use:

```shell
docker run -ti --name ktranslate-discovery --rm --net=host \
--user `id -u`:`id -g` \
-v `pwd`/snmp-base.yaml:/snmp-base.yaml \
kentik/ktranslate:v2 \
    -snmp /snmp-base.yaml \
    -log_level info \
    -snmp_discovery=true
```

**Comment by i3149** [comment]
Does the steps to reproduce work for you @thezackm ? I can't make `discovery.no_dedup_engine_id` go missing.

**Comment by thezackm** [comment]
I'll get a recording on the next test we run, scheduling with the customer for early January

**Comment by thezackm** [comment]
unable to repro at this time, closing this as a non-issue for now
