### ISSUE TITLE
🐛 Automatic matching on SysDescr isn't working for Barracuda

### ISSUE THREAD

**Issue by thezackm** [kentik/ktranslate#221]
## Synopsis

The automatic matching of profiles based on the `SysDescr` field that was added in [this commit](https://github.com/kentik/ktranslate/pull/178/commits/f4a8fef01faed0ff5e845af21d33066ec8fd02a6) doesn't seem to be working on Barracuda email gateways at the moment.

## Issue

Discovery jobs against Barracuda devices right now are matching the devices to the [net-snmp-yml](https://github.com/kentik/snmp-profiles/blob/main/profiles/kentik_snmp/_general/net-snmp.yml) profile based on their generic Linux sysOID of `1.3.6.1.4.1.8072.3.2.10`. However the expectation is that they would map to `barracuda-email-gateway.yml` based on the pattern in their `SysDescr` field.

## To Recreate

Run a discovery job against devices with the following values in their `SYSTEM-MIB` OIDs:

```
.1.3.6.1.2.1.1.1.0 = STRING: Barracuda Email Security Gateway
.1.3.6.1.2.1.1.2.0 = OID: .1.3.6.1.4.1.8072.3.2.10
```

**Comment by i3149** [comment]
Fix in https://github.com/kentik/snmp-profiles/pull/113

**Comment by thezackm** [comment]
thanks; we'll have the customer redeploy and get the results reported ASAP

**Comment by thezackm** [comment]
validated this workflow is working as expected on the latest version of the image - closing this issue as resolved
