### ISSUE TITLE
🐛 BUG: bgpPeerState is receiving improper values

### ISSUE THREAD

**Issue by thezackm** [kentik/ktranslate#222]
## Synopsis

We have observed across multiple environments and versions of ktranslate that the value of `bgpPeerState` is often returning outside of the [documented enumeration standard](https://github.com/librenms/librenms/blob/dc73154ae66c468890c742cf8313b23d5ddd48f0/mibs/BGP4-MIB#L195-L210) from the `BGP4-MIB`. *This is also reflected on the [bgp4-mib.yml](https://github.com/kentik/snmp-profiles/blob/0c265f9d281dcdc086f7841a174350e61c53bcc7/profiles/kentik_snmp/_general/bgp4-mib.yml#L19-L27) profile for ktranslate.*

## Issue

SNMP walks from various devices are returning valid data, with the following pattern: 

```
snmpwalk -v 2c -On -c $COMMUNITY $IP_ADDRESS .1.3.6.1.2.1.15.3.1.2
```

Results:
```
.1.3.6.1.2.1.15.3.1.2.10.3.254.6 = INTEGER: 6
.1.3.6.1.2.1.15.3.1.2.172.16.1.25 = INTEGER: 6
.1.3.6.1.2.1.15.3.1.2.172.16.2.9 = INTEGER: 6
.1.3.6.1.2.1.15.3.1.2.172.16.2.49 = INTEGER: 6
```

*Note the output pattern from this tabular OID is `OID.IP`, where `IP` is the address of the BGP peer, per the MIB. This is somewhat different than the standard SNMP table index.*

The results of the walk above show 4 BGP peers in `established: 6` status. However these are the results in New Relic:

![image](https://user-images.githubusercontent.com/30831476/147008028-ba97e188-fda9-4ed2-8bec-d96ac1a791fb.png)

Notice how there is a single entry that shows valid data; but then there are 3 extra entries with values prefixed to the `Index`. The running theory right now is that the ktranslate function that assigns `Index` values is basically creating one row per existing row in the table. So instead of each peer having a single row; each peer ends up with rows == total peer count.

You can see similar evidence here where we show all data for a single switch; and each is repeated 4X.

![image](https://user-images.githubusercontent.com/30831476/147008540-fb763d84-4707-45c3-a02d-c7c649ee349f.png)

## To Recreate

Run a current version of ktranslate against any device that supports the `BGP4-MIB`; this seems to be a universal problem based on the recurrence of log messages like this: 

```
2021-12-21T22:57:24.792 ktranslate/snmp [Warn] KTranslate><DEVICE_NAME> Missing enum value for device metric bgpPeerState 60
```

**Comment by i3149** [comment]
Thanks for this bug report -- this was a bad one! Above PR should address.

**Comment by i3149** [comment]
Should be good in latest build.
