### ISSUE TITLE
Receiving SNMP data from Dell Z9100 and 4128F Switches

### ISSUE THREAD

**Issue by htunceli** [kentik/ktranslate#226]
Hi,
We can read the snmp data of our palo alto devices via the ktranslate docker we have installed and send it to newrelic. However, we cannot extract data from our Dell Z9100 (OS Version: 10.5.2.3) and 4128F (OS Version: 10.5.2.3) switches with snmp. I think the related OIDs are not available in ktranslate. Is it possible for us to customize it? Where should we upload the mib files of our Dell switches in ktranslate? If you want a control output from Docker, I can share it here. I will be grateful if you could help me.
Have a nice day.

**Comment by thezackm** [comment]
greetings @htunceli! 

you can find documentation on [creating and managing SNMP profiles](https://docs.newrelic.com/docs/network-performance-monitoring/advanced/snmp-profiles/) in the New Relic docs site, where we overview both how to build and submit your profile for the community, as well as situations where you can build your own profile and upload it locally (outside of the OSS repository).

additionally, we can help build profiles for you if you will [submit an issue on the snmp-profiles repo](https://github.com/kentik/snmp-profiles/issues/new?assignees=&labels=profile&template=snmp-profile-request.md&title=%5BMissing+SNMP+Profile%5D) and upload SNMP walks from each device you'd like support for. 

thanks!
