### ISSUE TITLE
FR: Support AWS Secrets Manager JSON Secret Strings

### ISSUE THREAD

**Issue by araddas** [kentik/ktranslate#227]
The AWS Secrets Manager support requires a secret for each part of the SNMP credential configuration. This makes the management of the credentials in Secrets Manager a bit cumbersome. It would be ideal to either reference the keys within a JSON SecretString value to fill in the credentials, or set the JSON SecretString as the YAML configuration for default_v3 within the configuration file. 

**Example JSON SecretString**
```
MY_SM_SECRET_JSON = 
{
	"user_name": "username",
	"authentication_protocol": "MD5"
	"authentication_passphrase": "authpass",
	"privacy_protocol": "AES",
	"privacy_passphrase": "privpass"
}
```

**Key Reference Example**
```
default_v3: 
	user_name: aws.sm.$MY_SM_SECRET_JSON["user_name"]
	authentication_passphrase: aws.sm.$MY_SM_SECRET_JSON["authentication_passphrase"]
```

**SecretSting JSON as default_v3 value Example**
```
default_v3: aws.sm.$MY_SM_SECRET_JSON
```

**Comment by i3149** [comment]
This form should work now:

```
default_v3: aws.sm.$MY_SM_SECRET_YAML
```

I didn't want to support JSON as a config because the snmp config file is yaml and it seemed nasty to embed json in yaml. 

I tested with

```
MY_SM_SECRET_YAML = 
"user_name": "username"
"authentication_protocol": "MD5"
"authentication_passphrase": "authpass"
"privacy_protocol": "AES"
"privacy_passphrase": "privpass"
```

Let me know if this works for you

**Comment by araddas** [comment]
@i3149 I can confirm this is working as it should, thanks for the quick turn around!

**Comment by araddas** [comment]
@i3149  I may have spoke too soon, when I initially set the aws.sm under global and run discovery, it replaces that line (and all device snmp_v3 fields) with all of the values from the secret. Ideally the reference to aws.sm should stay in place instead of replacing the fields to ensure no secret information is stored on disk.


<img width="577" alt="Screen Shot 2022-01-05 at 12 45 33 PM" src="https://user-images.githubusercontent.com/24640633/148287468-c4390693-f969-4488-8b72-9e039862e37d.png">

**Comment by i3149** [comment]
Oh right! I didn't think this through for the discovery step. I will fix.

**Comment by i3149** [comment]
Try one more time. `default_v3: aws.sm.$MY_SM_SECRET_YAML` should not get overwritten on discovery now.

**Comment by araddas** [comment]
@i3149  I can confirm that nothing is getting overwritten and secrets are not being stored in the configuration files now. This is awesome and one of my last hurdles of getting this into production. Thank you!

**Comment by i3149** [comment]
Sweet! Closing this one. I wasn't sure what happened to #230 but that should be resolved now too.
