### ISSUE TITLE
Bug - entity description tag missing for cisco-all-devices profile.

### ISSUE THREAD

**Issue by araddas** [kentik/ktranslate#230]
The [cisco-all-devices profile](https://github.com/kentik/snmp-profiles/blob/main/profiles/kentik_snmp/cisco/cisco-all-devices.yml) has the entity_description tag defined, however, it is not populating values in New Relic. This information is valuable to define alert policies and provide context around what is actually being monitored. If this is an issue at the profile level please let me know and I will log it in a the other repo.

**Tag Reference in the Profile**

<img width="473" alt="Screen Shot 2022-01-05 at 8 34 26 AM" src="https://user-images.githubusercontent.com/24640633/148264187-1e0d9abe-f557-4163-b59f-aca0c10e6d69.png">

**Screenshot showing entity.description tag missing**

<img width="737" alt="Screen Shot 2022-01-05 at 8 35 52 AM" src="https://user-images.githubusercontent.com/24640633/148265093-61cd51eb-f7c6-4753-bf1e-58e9f3b62a30.png">

**SNMP Walk Verification**
```
[root]# snmpwalk .1.3.6.1.4.1.9.9.117.1.1.2.1.1.9000
SNMPv2-SMI::enterprises.9.9.117.1.1.2.1.1.9000 = INTEGER: 1

[root]# snmpwalk 1.3.6.1.2.1.47.1.1.1.1.2.9000
SNMPv2-SMI::mib-2.47.1.1.1.1.2.9000 = STRING: "Cisco Catalyst 9400 Series 48-Port UPOE w/ 24p mGig 24p RJ-45"
```

**Comment by i3149** [comment]
Looks like its because `entity_description` is defined in multiple MIBs. This should be supported but will need to tweak some code to make work.

**Comment by araddas** [comment]
@i3149 Looks great now
<img width="1299" alt="Screen Shot 2022-01-06 at 4 34 41 PM" src="https://user-images.githubusercontent.com/24640633/148472237-40e3c34a-4165-4275-98f0-0a305880b150.png">
