### ISSUE TITLE
Ktranslate logs inflating due to GETBULK being used on SNMPv1 instance, despite not being supported

### ISSUE THREAD

**Issue by ASchneider-GitHub** [kentik/ktranslate#235]
### Issue Summary
The customer currently has Ktranslate deployed, and is using it to get SNMP data from devices on a v1 network. The logs are inflating in size due to the error below being repeated every time a poll is run:
```
There was an SNMP polling error with the Counter walking OID <targetOID> after 0 retries: GETBULK not supported in SNMPv1.
```

### Reproduction Information
Customer currently has an SNMPv1 instance deployed on their network. They then deployed Ktranslate following the guide found here: https://docs.newrelic.com/docs/network-performance-monitoring/setup-performance-monitoring/snmp-performance-monitoring/#setup-snmp-monitoring

### Additional Information
Redacted log and configuration files have been attached:

- [c590b0cc02fa2fbe8f6f5469012eb069b7aff6d16972ff1ed214e62aab9618e8-json.log](https://github.com/kentik/ktranslate/files/7850634/c590b0cc02fa2fbe8f6f5469012eb069b7aff6d16972ff1ed214e62aab9618e8-json.log)
- [snmp-base.yaml.txt](https://github.com/kentik/ktranslate/files/7850635/snmp-base.yaml.txt)

**Comment by i3149** [comment]
Good call out here. I'll update this logic.

**Comment by i3149** [comment]
Should be good now with the latest build.
