### ISSUE TITLE
💡 FR: Better handling of String-valued OIDs

### ISSUE THREAD

**Issue by thezackm** [kentik/ktranslate#252]
As a user, I need the ability to poll all OIDs at various intervals, regardless of their data type. Today, we place OIDs that return string values as `metric_tags` to decorate the actual integer/float `metrics` that are received on a device or SNMP table for a device. This pattern works well mot of the time, but is limited in situations where the vendor uses a string-valued OID to report status or status messages. Since `metric_tags` are polled at a 3-hour interval as "inventory" style data, this risks missing critical signals in my telemetry.

A possible work-around could be to have **ktranslate** detect string-values in `metrics` and automatically decorate them as attributes in the same way we handle `enum` today. This allows me to push my OID collection into the standard polling interval for these edge cases where I need my string-value results to stay in sync with my traditional metrics.

**Comment by i3149** [comment]
Closing this one out until we need more.
