### ISSUE TITLE
32-bits support

### ISSUE THREAD

**Issue by mmattos-newrelic** [kentik/ktranslate#256]
My customer is implementing NPM, and some routers were not working. Looking at the "mibs" and the code, only the 64-bit counters are expected, e.g., ifHCInOctets. However, the router they are monitoring has only 32-bit counters, e.g., ifInOctets.

An essential piece of information is that all the other monitoring competitors they tested (check-mk, observium, prometheus, telegraf), already have 64 and 32-bit counters by default.

So having these accountants is extremely important for both this customer and others.

**Comment by i3149** [comment]
Could this be done via a new profile in https://github.com/kentik/snmp-profiles? 

By default these OIDs are used: https://github.com/kentik/snmp-profiles/blob/main/profiles/kentik_snmp/_general/if-mib.yml
But other ones can be specified for a given device. If you can, I would recommend you submit a profile for the target device here as a PR to this repo. Thanks!

**Comment by thezackm** [comment]
addressing in kentik/snmp-profiles#224
