### ISSUE TITLE
FR: Firehose Syn enhancements (timestamp, labels, per-agent metrics)

### ISSUE THREAD

**Issue by axehayz** [kentik/ktranslate#261]
copy paste from SFDC FR case: 9697 (https://kentik.lightning.force.com/lightning/r/Case/5003m00001HNXSrAAP/view)

Customer is building a datalake that integrates several data sources in Elastic Kibana. For context, these include updown metrics, catchpoint data and Kentik data (via firehose). Using firehose as customer prefers a "drop-in" push model versus writing logic for API pull. We are successful in plumbing of this circuitry, however they are requesting additional metrics to be able to make data more usable.

Specifically, requesting to include test timestamps, test labels, and per-agent measurements per test to be included in firehose.

Additionally, would like to include high-level test summary in the json output.

P.S: Could not find ktranslate product component, and didnt want to overcrowd synthetics FRs. Hence putting in "Other".

**Comment by i3149** [comment]
Added these in.
