### ISSUE TITLE
Bug: syslog sometimes missing device_name/hostname

### ISSUE THREAD

**Issue by jbeveland27** [kentik/ktranslate#284]
@jbiggley was looking through syslog data and noticed that `device_name` and `hostname` are empty (Josh - please correct if that's wrong). When that occurs the log is relatively meaningless since there's no way to know which device it was associated with.

There's a fallback present [here](https://github.com/kentik/ktranslate/blob/main/pkg%2Finputs%2Fsyslog%2Fsyslog.go#L188-L193) where the hostname is used if the device_name is empty, but it might be more robust to do a dns lookup if the dns flag is set.

**Comment by i3149** [comment]
Should we enforce `hostname` being populated always? Right now, this may or may not be populated, but `device_name` always should be.

**Comment by jbeveland27** [comment]
`device_name` is good. Thanks!
