### ISSUE TITLE
Bug: response_time PacketLossPct reporting nonsense values

### ISSUE THREAD

**Issue by Mesverrum** [kentik/ktranslate#288]
I ran into this in a customer account and was able to duplicate it in my test environment, with reponse_time: true globally  kentik.ping.PacketLossPct seems to always be returning  -9223372036854776.  I would expect this should be 0 in the places I tested it.

**Comment by i3149** [comment]
This is an artifact of when the ping is not getting returned. Likely will be fixed by setting this env var: `KENTIK_PING_PRIV=true` 

This changes ping from UDP to ICMP based packets.

**Comment by drhythm** [comment]
Hi @i3149 is this a change that the customer would make in their environment, or should we wait for a new container version to be released?

Also, I just want to confirm how this works... so the desired output = 0.. and if the returned value is more than 0, that means the node is down / not responding to ping ?
