### ISSUE TITLE
Possible error with poll_time_sec for if-mib

### ISSUE THREAD

**Issue by Mesverrum** [kentik/ktranslate#305]
Despite having poll_time_sec: 60 it looks like ifHCInOctets is polling at the same rate as my customer's global interval, 120s.  On the UI side I am seeing IfUtilization coming in every ~60s but it is alternative between 0's the expected calculation.

Any chance the IF mib still has some lingering special code that is that is ignoring poll_time_sec?

**Comment by Mesverrum** [comment]
Sample data from a customer account

March 31, 2022 15:25:19 kentik.snmp.ifHCInOctets {"type":"count","count":2516.0}
March 31, 2022 15:25:19 kentik.snmp.IfInUtilization {"type":"gauge","count":1,"sum":3.1E-5,"min":3.1E-5,"max":3.1E-5,"latest":3.1E-5}
March 31, 2022 15:24:14 kentik.snmp.IfInUtilization {"type":"gauge","count":1,"sum":0.0,"min":0.0,"max":0.0,"latest":0.0}
March 31, 2022 15:23:19 kentik.snmp.ifHCInOctets {"type":"count","count":8679.0}
March 31, 2022 15:23:19 kentik.snmp.IfInUtilization {"type":"gauge","count":1,"sum":1.07E-4,"min":1.07E-4,"max":1.07E-4,"latest":1.07E-4}
March 31, 2022 15:22:14 kentik.snmp.IfInUtilization {"type":"gauge","count":1,"sum":0.0,"min":0.0,"max":0.0,"latest":0.0}
March 31, 2022 15:21:19 kentik.snmp.ifHCInOctets {"type":"count","count":2516.0}
March 31, 2022 15:21:19 kentik.snmp.IfInUtilization {"type":"gauge","count":1,"sum":3.7E-5,"min":3.7E-5,"max":3.7E-5,"latest":3.7E-5}
March 31, 2022 15:20:24 kentik.snmp.IfInUtilization {"type":"gauge","count":1,"sum":0.0,"min":0.0,"max":0.0,"latest":0.0}
March 31, 2022 15:19:19 kentik.snmp.ifHCInOctets {"type":"count","count":2515.0}
March 31, 2022 15:19:19 kentik.snmp.IfInUtilization {"type":"gauge","count":1,"sum":3.1E-5,"min":3.1E-5,"max":3.1E-5,"latest":3.1E-5}
March 31, 2022 15:18:14 kentik.snmp.IfInUtilization {"type":"gauge","count":1,"sum":0.0,"min":0.0,"max":0.0,"latest":0.0}
March 31, 2022 15:17:19 kentik.snmp.ifHCInOctets {"type":"count","count":7352.0}
March 31, 2022 15:17:19 kentik.snmp.IfInUtilization {"type":"gauge","count":1,"sum":9.1E-5,"min":9.1E-5,"max":9.1E-5,"latest":9.1E-5}
March 31, 2022 15:16:14 kentik.snmp.IfInUtilization {"type":"gauge","count":1,"sum":0.0,"min":0.0,"max":0.0,"latest":0.0}

**Comment by i3149** [comment]
Yes, very likely. Will check.
