### ISSUE TITLE
High CPU Load on latest image

### ISSUE THREAD

**Issue by araddas** [kentik/ktranslate#331]
I recently updated our image from "kt-2022-03-29-2059178585" to "kt-2022-06-02-2429956899", after doing so the CPU load has increase 40% over the previous version. 
<img width="489" alt="Screen Shot 2022-06-02 at 11 54 25 AM" src="https://user-images.githubusercontent.com/24640633/171710460-c0ce52fc-1739-4bed-9d08-2a1ab623e09f.png">

**Comment by i3149** [comment]
Are you using `response_time` or `ping_only` on any of these devices to run ping checks? The only change I can think of here which could cause this is that the ping rate went from 1/min to 1/sec by default.

**Comment by i3149** [comment]
There's `ping_interval_sec` to change but this is set per device. I'll add a global option to change this for all devices.

**Comment by i3149** [comment]
@araddas , Try out setting `ping_interval_sec: 60` in the global section also and see how this looks, with the latest image. 

```
global:
...
  ping_interval_sec: 60
...
```

As an example.

**Comment by araddas** [comment]
@i3149 the new image appears to have fixed the high load after we added `ping_interval_sec: 60` to all of our configuration files.

**Comment by i3149** [comment]
Great, sorry for changing this default. I'll probably move back to 1 ping/min default going forward.
