### ISSUE TITLE
🐛  - UDP port forwarding is not working for KTranslate

### ISSUE THREAD

**Issue by thezackm** [kentik/ktranslate#332]
## Problem

We have observed that Docker's UDP port forwarding is not working with the KTranslate container image.

## Environment

KTranslate Version:
```
Repo Digest: kentik/ktranslate@sha256:6f2b21a5b6a7521bfd361cd4029cd4da634d94500e7246bd79f4ded45bc9de3f
Created: 2022-05-31T23:37:51.410178438Z
```

Docker Version:
```
 Engine:
  Version:          20.10.16
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.10
  Git commit:       f756502
  Built:            Thu May 12 09:15:28 2022
  OS/Arch:          linux/amd64
  Experimental:     false
```

Docker Host: 
```
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
```

## Replicate the issue

Run a container with port forwarding enabled for both UDP and TCP to redirect host port 162 >> container port 1620
```
docker run -ti --name ktranslate-traps-forward --restart unless-stopped -p 162:1620/udp -p 162:1620/tcp \
kentik/ktranslate:v2 \
  -snmp /etc/ktranslate/snmp-base.yaml \
  -format=new_relic_metric \
  -sinks=stdout
```

Send a test SNMP trap to host port 162 (UDP)
```
snmptrap -v 2c -c hello 127.0.0.1:162 '' 1.3.6.1.4.1.8072.2.3.0.1 1.3.6.1.4.1.8072.2.3.2.1 i 123456
```

## Expected results

You should see a log entry in KTranslate's container logs like this:
```
2022-06-02T18:20:08.769 ktranslate [Info] KTranslate got trapdata from 127.0.0.1
```

## Validated Tests

Using the host network and host port 1620/udp works as expected:
```
docker run -ti --name ktranslate-traps-host --restart unless-stopped --net=host \
kentik/ktranslate:v2 \
  -snmp /etc/ktranslate/snmp-base.yaml \
  -format=new_relic_metric \
  -sinks=stdout
```

```
snmptrap -v 2c -c hello 127.0.0.1:1620 '' 1.3.6.1.4.1.8072.2.3.0.1 1.3.6.1.4.1.8072.2.3.2.1 i 123456
```

---

And using a `netcat` container work for port forwarding UDP in general:
```
docker run -it -p 5000:5000/udp --rm tiborvass/netcat nc -l -u -p 5000
```

Connect to the container from another terminal
```
nc -u 127.0.0.1
```

Type a test message and hit **enter** to send
![Image 2022-06-02 at 1 58 34 PM](https://user-images.githubusercontent.com/30831476/171711876-b96eea6f-289e-4ac4-a81a-3ea18952d53f.jpg)

Results in the container:
![Image 2022-06-02 at 1 59 11 PM](https://user-images.githubusercontent.com/30831476/171712389-ed0647e2-2a3d-42b1-b119-a939111cf6ee.jpg)

**Comment by sskilbred** [comment]
Would it be possible to get an update on this issue?

**Comment by i3149** [comment]
I'm not able to reproduce this in my dev environment. 

I do see one pitfall however which I bet you are hitting. In the `trap` section of snmp.yaml, be sure to set listen to be `listen: 0.0.0.0:1620`. By default it listens on 127.0.0.1 only, which because of the way docker networking is set up means its not listening to the `docker0` interface where packets from the outside world come in. For example:

```
trap:
  listen: 0.0.0.0:1620
  community: hello
  version: ""
  transport: ""
  v3_config: null
```

With this changed and running like:

```
 docker run -ti --rm --name ktranslate-traps-forward -p 162:1620/udp -v `pwd`/snmp-docker.yaml:/snmp.yaml kentik/ktranslate:v2   -snmp /snmp.yaml   -format=new_relic_metric   -sinks=stdout
```

Your test command

```
 snmptrap -v 2c -c hello 127.0.0.1:162 '' 1.3.6.1.4.1.8072.2.3.0.1 1.3.6.1.4.1.8072.2.3.2.1 i 123456
```

Produces the desired response:

```
2022-07-14T21:51:50.531 ktranslate [Info] KTranslate got trapdata from 172.17.0.1
```

**Comment by thezackm** [comment]
confirmed this change to the config file has the desired effect on the latest image via a test machine.
