### ISSUE TITLE
💡 FR - Azure Key Vault Support

### ISSUE THREAD

**Issue by thezackm** [kentik/ktranslate#334]
As a user, I need to leverage [Azure Key Vault](https://docs.microsoft.com/en-us/azure/key-vault/secrets/quick-create-go) to manage my sensitive configuration information for ktranslate, in the same manner that is currently supported with [AWS Secrets Manager](https://github.com/kentik/ktranslate/blob/main/pkg/kt/aws.go).

**Comment by i3149** [comment]
I added a test version of this into the `kentik/ktranslate:next` image. Run by first setting the 

`KT_AZURE_KEY_VAULT_NAME` environment variable. This is added to the string `https://%s.vault.azure.net/` to produce the url to hit for this vault. 

Then set `snmp_v3: azure.kv.my_key_name` in the snmp.yaml config. The value of `my_key_name` in the vault `KT_AZURE_KEY_VAULT_NAME` will be parsed as yaml and placed into the v3 config.

**Comment by i3149** [comment]
Added. Also an optional `KT_AZURE_KEY_VAULT_URL` if you want to specify a key vault url which isn't of the form `https://%s.vault.azure.net/`
