### ISSUE TITLE
💡 FR - GCP Secret Manager Support

### ISSUE THREAD

**Issue by thezackm** [kentik/ktranslate#335]
As a user, I need to leverage [GCP Secret Manager](https://cloud.google.com/secret-manager/docs/create-secret#secretmanager-quickstart-go) to manage my sensitive configuration information for ktranslate, in the same manner that is currently supported with [AWS Secrets Manager](https://github.com/kentik/ktranslate/blob/main/pkg/kt/aws.go).

**Comment by i3149** [comment]
I added a test version of this into the `kentik/ktranslate:next` image.

To run, set `snmp_v3: gcp.sm.my_secret_name` in the snmp.yaml config. The value of `my_secret_name` in GCP Secret Manager will be parsed as yaml and placed into the v3 config. You can use any of the following formats to reference a secret:

```
gcp.sm.<name>
gcp.sm.<name>/<version>
gcp.sm.<project>/<name>
gcp.sm.<project>/<name>/<version>
gcp.sm.projects/<project>/secrets/<name>/versions/<version>
```

**Comment by i3149** [comment]
Added.
