### ISSUE TITLE
Wiki page Sample-SNMP-config has incorrect privacy_protocol options

### ISSUE THREAD

**Issue by nedl86** [kentik/ktranslate#357]
Wiki page [Sample-SNMP-config](https://github.com/kentik/ktranslate/wiki/Sample-SNMP-config) shows the possible values for `privacy_protocol` as:

[AuthNoPriv|DES|AES|AES192|AES256|AES192C|AES256C]

But the valid options [are actually](https://github.com/kentik/ktranslate/blob/17847413c488bad07a0dfec1de46a447406077eb/pkg/inputs/snmp/util/adaptor.go#L50):

[NoPriv|DES|AES|AES192|AES256|AES192C|AES256C]

Can this please be corrected? It doesn't look like these wiki pages can be edited by regular users otherwise I'd propose the update myself. Thanks!

**Comment by i3149** [comment]
Great catch -- thanks!
