### ISSUE TITLE
FR: allow multiple tags using the same OID

### ISSUE THREAD

**Issue by dpajin-kentik** [kentik/ktranslate#402]
I would like to be able to create multiple tags which are using the same OID.
Currently it seems that this is not possible and it is not completely clear to me why.
Here is the example of what I am trying to do:
```
  - tag: os_name
    column:
      OID: 1.3.6.1.2.1.1.1.0
      name: sysDescr
      regexp: kernel\s+(\w+)\s+[\w\.\-]+,
  - tag: os_version
    column:
      OID: 1.3.6.1.2.1.1.1.0
      name: sysDescr  
      regexp: kernel\s+\w+\s+([\w\.\-]+),
```
even if I put the unique "name", instead of sysDescr, this will not work as it might be overlapping with the sysDescr in system-mib or with something which is hardcoded....

**Comment by i3149** [comment]
Will support multiple `conversion:` values to different tags.

**Comment by tdanner** [comment]
As an alternative to specifying which RE capture group to use, you can make all but one of them non-capturing groups. Like this: `(?:version|kernel)`.
