### ISSUE TITLE
FR: Submit discovery data to NerdGraph

### ISSUE THREAD

**Issue by jbeveland27** [kentik/ktranslate#414]
Related to #413 - when running in `--remote_config` mode (or maybe just whenever we know nr1 is the sink via `nr1.snmp`/`nr1.netflow`/`nr1.syslog` flags) , after discovery runs we need to submit the configuration to NerdGraph (see [architectural diagram](https://whimsical.com/ktranslate-configuration-lifecycle-QHzcSviKa2Gug4F8Sohkay) for more info)

![image](https://user-images.githubusercontent.com/6722433/187446413-3464a209-f00e-48c6-a857-5dca81b60ff2.png)

**Comment by i3149** [comment]
Gonna close this for now because I think we're going in a different direction.
