### ISSUE TITLE
FR: Generate a persistent and unique identifier whenever ktranslate is installed

### ISSUE THREAD

**Issue by jbeveland27** [kentik/ktranslate#415]
Related to #413 / #414 - we need to uniquely identify each running instance of ktranslate to identify a saved config when querying/mutation from NerdGraph.

This UUID will need to be persisted somewhere locally and remain the same between restarts and upgrades of ktranslate. For containerized deployment we could use a volume. For packaged installs, perhaps the `/etc/default/ktranslate.env` file? Open to suggestions, but just want to emphasize that the solution needs to be durable to avoid losing the config and ending up in an unexpected state.

**Comment by i3149** [comment]
Gonna close this for now because I think we decided to go in a different direction but can re-open if we change our minds.
