### ISSUE TITLE
ktranslate/firehose influx issue

### ISSUE THREAD

**Issue by dpajin-kentik** [kentik/ktranslate#424]
Kentik customer issue https://github.com/kentik/ui-app/issues/14010

**Comment by i3149** [comment]
Summary
firehose/ktransalte not working as expected for influxdb

Description
it is not generating any data on bucket

docker run -p 8082:8082 kentik/ktranslate -format influx -sinks http -http_url=http://localhost:8086/write?db=kentik -listen=0.0.0.0:8082

Fix in #419
