### ISSUE TITLE
FR: Assign device_name after DNS lookup

### ISSUE THREAD

**Issue by sskilbred** [kentik/ktranslate#457]
The DNS lookup for traps was implemented not long ago, and it works fine. The only gap is that the device_name remains the ip-address. It would make sense to update the device_name with the name returned by the DNS.

Note: This already works when the device-name has been added to the devices config.

**Comment by i3149** [comment]
Can you give an example of where you are still seeing the IP in the `device_name` field? From my testing, data should look like:

```
  {
    "instrumentation.name": "netflow-events",
    "device_name": "localhost",
    "src_addr": "127.0.0.1",
    ...
  }```

After dns resolution.

**Comment by sskilbred** [comment]
Here is one example from a customer (I masked some of the IPs, but they match). 
> {
>     "device_name": "172.xx.xxx.39",
>     "src_addr": "172.xx.xxx.39",
>     "src_host": "loncd.uk.mycomp.com"
>   }

**Comment by i3149** [comment]
OK, this feels like a bug and the reverse dns not working. Let me dig more.
