### ISSUE TITLE
FR: The InfluxDB measurement name for SNMP metric collections

### ISSUE THREAD

**Issue by dpajin-kentik** [kentik/ktranslate#488]
The InfluxDB measurement name for SNMP metric collections can be constructed in the following way:

- If the MIB name is empty string (this happens if the metric is scalar and defined without MIB key):
    - measurement name = “device”

- If the MIB name starts with “/” - want to be able to normalize SNMP metadata and metrics to the structure similar to YANG models
    - Remove last “/” from MIB name (if exist) and first “/” from table name (if exist) and 
    - measurement name = MIB + “/” + Table

- If the MIB name does not start with “/” - this are "normal" SNMP OID names, which usually representation is "MIB::Table"
    - measurement name = MIB + “::” + Table

**Comment by i3149** [comment]
Think this one is handled now.
