### ISSUE TITLE
FR: Allow discovery to iterate testing v3>v2>v1 automatically

### ISSUE THREAD

**Issue by Mesverrum** [kentik/ktranslate#494]
As a user with a mixed environment where a small number of devices scattered throughout the subnets only support v1 it is a chore to separate out the v1 devices for their own discovery jobs.

From a customer "What I’d expect to see is: check snmpv3 > check snmpv2c >check snmpv1. Sadly, we do have SNMPv1 devices in our environment."

**Comment by i3149** [comment]
The challenge here is that checking each version will increase the time taken to do a disco. 

How about if there's an optional `versionOneAndTwo` bool in the disco config? Defaults to false which is the current behavior. If true, will check 2 and then 1. Currently version 3 is checked first and then version 2c or 1.
