### ISSUE TITLE
Trying to pass snmp v3 env variables but not working

### ISSUE THREAD

**Issue by Cannoli-spec** [kentik/ktranslate#503]
From New Relic customer:
So i tried making v3 a single env variable, it said that it needed a valid privacy protocol (thus its still getting null values)
So then I tried to set separate env variables just for tokens but again, it just overwrites my values with null values:
Before container run:
    user_name: random
    authentication_protocol: SHA
    authentication_passphrase: ${v3authtok}
    privacy_protocol: AES
    privacy_passphrase: ${v3privtok}
    context_engine_id: ""
    context_name: ""
Once container starts:
    user_name: random
    authentication_protocol: SHA
    authentication_passphrase: ""
    privacy_protocol: AES
    privacy_passphrase: ""
    context_engine_id: ""
    context_name: ""

**Comment by Cannoli-spec** [comment]
So i tried making v3 a single env variable, it said that it needed a valid privacy protocol (thus its still getting null values)
So then I tried to set separate env variables just for tokens but again, it just overwrites my values with null values:
Before container run:
    user_name: random
    authentication_protocol: SHA
    authentication_passphrase: ${v3authtok}
    privacy_protocol: AES
    privacy_passphrase: ${v3privtok}
    context_engine_id: ""
    context_name: ""
Once container starts:
    user_name: random
    authentication_protocol: SHA
    authentication_passphrase: ""
    privacy_protocol: AES
    privacy_passphrase: ""
    context_engine_id: ""
    context_name: ""

**Comment by i3149** [comment]
I wonder if somehow the env vars are not getting picked up like you think. Can you run this command and provide the (redacted) output: 

```
docker run -it --rm --entrypoint printenv kentik/ktranslate:v2
```

The error about `needing a valid privacy protocol` generally means that the v3 config isn't getting picked up at all.
