### ISSUE TITLE
Discovery misses some hosts

### ISSUE THREAD

**Issue by tdanner** [kentik/ktranslate#529]
Please see extended discussion: https://kentik.slack.com/archives/C03MQCJ1Z2Q/p1677232845830249

In this case, there was a host that did respond to SNMP but was not picked up by ktranslate. I did some investigation but it wasn't really conclusive. ktranslate uses `DeviceScanner.Scan()` from https://github.com/liamg/furious. This method seems to ignore the provided port list and instead attempts to connect to TCP port 1. As this port is used by no one and is likely firewalled everywhere, I don't understand how this works at all. Needs more investigation.

**Comment by i3149** [comment]
There's a known bug where a basic disco scan will see that hosts are down when they are actually up. Two ways that the system can work around this are:

1) Specify a `/32` range for known devices which are not getting picked up. This forces ktrans to double check these IPs. 

2) https://docs.newrelic.com/docs/network-performance-monitoring/advanced/advanced-config/#discovery

Set this variable to true in the config file: `check_all_ips`

From the docs:

```
When set to true, forces the discovery job to attempt SNMP connectivity against every target IP address from the cidrs array, without checking for liveliness first via TCP port scan. This setting will slow down discovery jobs, but can help bypass issues where discovery is failing against devices that are not listed in your cidrs array with /32 overrides. By default, it's set to false
```

**Comment by tdanner** [comment]
What is the known bug? I'm just wondering what causes this.

**Comment by i3149** [comment]
Scanner is doing this:

```
			conn, err := net.DialTimeout("tcp", fmt.Sprintf("%s:1", ip.String()), s.timeout)
```

This is blocked by some firewalls so ktrans thinks that the device is down. Not really a bug I guess? More of a feature.

**Comment by tdanner** [comment]
The way I see it, the desired behavior is for this to find all hosts that could be monitored with the available SNMP credentials. Networks are complicated, it's probably not possible to do this perfectly.

This is a case where the check excluded a valid host. I think we should consider whether there is some reasonable way to modify the check in a way that reduces these false negatives without causing other problems. For example, instead of testing TCP port 1 (???), what if we test port 22 instead?

**Comment by i3149** [comment]
Maybe you could use syn scan also? This requires root which is why I didn't pick it but could be an option. Or separately, connect option does take the port param so could be used too.
