### ISSUE TITLE
Floating point precision is limited to 3 decimal places

### ISSUE THREAD

**Issue by kentik-will** [kentik/ktranslate#533]
Floating point values output by Starlark scripts are currently limited to 3 decimal places of precision due to being stored in integer columns by this code: 

https://github.com/kentik/ktranslate/blob/159f61bc41f2b6ab5fc537a795c19e5c81d80cb8/pkg/util/enrich/mib_metric.go#L128

Greater precision is desired, should separate storage of floats be added or an arbitrary higher amount of precision selected?

**Comment by tdanner** [comment]
Yes, I think we should add `floats map[string] float64` to `MibMetric` and track them separately. While SNMP doesn't have native floats, there are a number of scenarios for converting SNMP data to float via Starlark.
