### ISSUE TITLE
 Device stop forwarding the docker container logs periodically

### ISSUE THREAD

**Issue by jvadera** [kentik/ktranslate#534]
I am TSE at Newrelic 

Raising the issue on behalf of the customer

**Issue in their own words**

We have the Meraki polling engine stop forwarding the docker container logs periodically. It happens every 6-7 days for the EU & US polling engines mainly. This impact directly on device monitoring which is crucial to us.
Below container log chart link clearly shows the gap in log forwarding

**NRQL used to test**

FROM Metric
SELECT
average(kentik.ktranslate.chf.kkc.delivery_logs_nr) AS 'delivery_logs_nr'
FACET host, svc
WHERE instrumentation.provider = 'kentik'
AND instrumentation.name = 'heartbeat' AND svc ='vma3gspx004_us_snmp' SINCE 4 weeks ago

**Customer is getting below log in EU container which stops sending logs to NR **

panic: runtime error: invalid memory address or nil pointer dereference

[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x13fe04b]

goroutine 2884 [running]:

github.com/kentik/ktranslate/pkg/inputs/snmp/metrics.(*DeviceMetrics).pollFromConfig(0xc00c02b920, {0x2251600, 0xc004f96000}, 0xc00abfda20?, 0x0?)

        /src/pkg/inputs/snmp/metrics/device_metrics.go:147 +0xcab

github.com/kentik/ktranslate/pkg/inputs/snmp/metrics.(*DeviceMetrics).Poll(...)

        /src/pkg/inputs/snmp/metrics/device_metrics.go:81

github.com/kentik/ktranslate/pkg/inputs/snmp/metrics.(*Poller).Poll(0xc00c02b8c0, {0x2251600, 0xc004f96000})

        /src/pkg/inputs/snmp/metrics/poll.go:244 +0x52

github.com/kentik/ktranslate/pkg/inputs/snmp.launchSnmp.func1()

        /src/pkg/inputs/snmp/snmp.go:307 +0x5c

created by github.com/kentik/ktranslate/pkg/inputs/snmp.launchSnmp

        /src/pkg/inputs/snmp/snmp.go:300 +0x4ac

panic: runtime error: invalid memory address or nil pointer dereference

[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x13fe04b]

 

goroutine 9085 [running]:

github.com/kentik/ktranslate/pkg/inputs/snmp/metrics.(*DeviceMetrics).pollFromConfig(0xc00ef6b140, {0x2251600, 0xc00225d100}, 0xc0095b86e0?, 0x0?)

        /src/pkg/inputs/snmp/metrics/device_metrics.go:147 +0xcab

github.com/kentik/ktranslate/pkg/inputs/snmp/metrics.(*DeviceMetrics).Poll(...)

        /src/pkg/inputs/snmp/metrics/device_metrics.go:81

github.com/kentik/ktranslate/pkg/inputs/snmp/metrics.(*Poller).Poll(0xc00ef6b0e0, {0x2251600, 0xc00225d100})

        /src/pkg/inputs/snmp/metrics/poll.go:244 +0x52

github.com/kentik/ktranslate/pkg/inputs/snmp.launchSnmp.func1()

        /src/pkg/inputs/snmp/snmp.go:307 +0x5c

created by github.com/kentik/ktranslate/pkg/inputs/snmp.launchSnmp

        /src/pkg/inputs/snmp/snmp.go:300 +0x4ac

panic: runtime error: invalid memory address or nil pointer dereference

[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x13fe04b]

 

goroutine 3302 [running]:

github.com/kentik/ktranslate/pkg/inputs/snmp/metrics.(*DeviceMetrics).pollFromConfig(0xc00d8d1920, {0x2251600, 0xc001d80000}, 0xc00da391e0?, 0x0?)

        /src/pkg/inputs/snmp/metrics/device_metrics.go:147 +0xcab

github.com/kentik/ktranslate/pkg/inputs/snmp/metrics.(*DeviceMetrics).Poll(...)

        /src/pkg/inputs/snmp/metrics/device_metrics.go:81

github.com/kentik/ktranslate/pkg/inputs/snmp/metrics.(*Poller).Poll(0xc00d8d18c0, {0x2251600, 0xc001d80000})

        /src/pkg/inputs/snmp/metrics/poll.go:244 +0x52

github.com/kentik/ktranslate/pkg/inputs/snmp.launchSnmp.func1()

        /src/pkg/inputs/snmp/snmp.go:307 +0x5c

created by github.com/kentik/ktranslate/pkg/inputs/snmp.launchSnmp

        /src/pkg/inputs/snmp/snmp.go:300 +0x4ac

panic: runtime error: invalid memory address or nil pointer dereference

[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x13fe04b]

 

goroutine 328 [running]:

github.com/kentik/ktranslate/pkg/inputs/snmp/metrics.(*DeviceMetrics).pollFromConfig(0xc0037db1a0, {0x2251600, 0xc002c40000}, 0xc0038aab00?, 0x0?)

        /src/pkg/inputs/snmp/metrics/device_metrics.go:147 +0xcab

github.com/kentik/ktranslate/pkg/inputs/snmp/metrics.(*DeviceMetrics).Poll(...)

        /src/pkg/inputs/snmp/metrics/device_metrics.go:81

github.com/kentik/ktranslate/pkg/inputs/snmp/metrics.(*Poller).Poll(0xc0037db140, {0x2251600, 0xc002c40000})

        /src/pkg/inputs/snmp/metrics/poll.go:244 +0x52

github.com/kentik/ktranslate/pkg/inputs/snmp.launchSnmp.func1()

        /src/pkg/inputs/snmp/snmp.go:307 +0x5c

created by github.com/kentik/ktranslate/pkg/inputs/snmp.launchSnmp

        /src/pkg/inputs/snmp/snmp.go:300 +0x4ac

panic: runtime error: invalid memory address or nil pointer dereference

[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x13fe04b]

 

goroutine 4950 [running]:

github.com/kentik/ktranslate/pkg/inputs/snmp/metrics.(*DeviceMetrics).pollFromConfig(0xc01129a1e0, {0x2251600, 0xc003afe980}, 0xc0014b3b80?, 0x0?)

        /src/pkg/inputs/snmp/metrics/device_metrics.go:147 +0xcab

github.com/kentik/ktranslate/pkg/inputs/snmp/metrics.(*DeviceMetrics).Poll(...)

        /src/pkg/inputs/snmp/metrics/device_metrics.go:81

github.com/kentik/ktranslate/pkg/inputs/snmp/metrics.(*Poller).Poll(0xc01129a180, {0x2251600, 0xc003afe980})

        /src/pkg/inputs/snmp/metrics/poll.go:244 +0x52

github.com/kentik/ktranslate/pkg/inputs/snmp.launchSnmp.func1()

        /src/pkg/inputs/snmp/snmp.go:307 +0x5c

created by github.com/kentik/ktranslate/pkg/inputs/snmp.launchSnmp

        /src/pkg/inputs/snmp/snmp.go:300 +0x4ac

panic: runtime error: invalid memory address or nil pointer dereference

[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x13fe04b]

 

goroutine 8360 [running]:

github.com/kentik/ktranslate/pkg/inputs/snmp/metrics.(*DeviceMetrics).pollFromConfig(0xc01f088960, {0x2251600, 0xc000908140}, 0xc01c1fe160?, 0x0?)

        /src/pkg/inputs/snmp/metrics/device_metrics.go:147 +0xcab

github.com/kentik/ktranslate/pkg/inputs/snmp/metrics.(*DeviceMetrics).Poll(...)

        /src/pkg/inputs/snmp/metrics/device_metrics.go:81

github.com/kentik/ktranslate/pkg/inputs/snmp/metrics.(*Poller).Poll(0xc01f088900, {0x2251600, 0xc000908140})

        /src/pkg/inputs/snmp/metrics/poll.go:244 +0x52

github.com/kentik/ktranslate/pkg/inputs/snmp.launchSnmp.func1()

        /src/pkg/inputs/snmp/snmp.go:307 +0x5c

created by github.com/kentik/ktranslate/pkg/inputs/snmp.launchSnmp

        /src/pkg/inputs/snmp/snmp.go:300 +0x4ac

panic: runtime error: invalid memory address or nil pointer dereference

[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x13fe04b]

**Comment by i3149** [comment]
Is it possible to get the version of ktranslate that the customer is running? Look for a log line like:

```
2023-03-07T23:13:42.002 ktranslate/ [Info]  version kt-2023-03-02-4309796445 starting
```

Thanks.

**Comment by jvadera** [comment]
@i3149 

They are using version kt-2023-02-24-4267053092

**Comment by tvranicar** [comment]
They are no longer sending data because of the apparent memory issue.
