### ISSUE TITLE
if device SNMP polling fails, there is no report on influx output

### ISSUE THREAD

**Issue by dpajin-kentik** [kentik/ktranslate#543]
I am trying to poll the device using wrong SNMP community and there is no indication on influxdb output that SNMP polling fails.
There are only ping results:
```
computed,device_ip=10.254.101.51,device_name=pdu101a.iad2,src_as_name=Private\ IP,src_geo=Private\ IP,tags.collector=dpajin_shell01,tags.dc=iad2,tags.site=iad,tags.type=pdu PacketsSent=1i,PacketsRecv=1i,StdDevRtt=0,PacketLossPct=0 1678451589
computed,device_ip=10.254.101.51,device_name=pdu101a.iad2,src_addr=10.254.101.51,src_as_name=Private\ IP,src_geo=Private\ IP,tags.collector=dpajin_shell01,tags.dc=iad2,tags.site=iad,tags.type=pdu MinRttMs=0.925,MaxRttMs=0.925,AvgRttMs=0.925 1678451589
```

**Comment by dpajin-kentik** [comment]
cc @tdanner

**Comment by kentik-will** [comment]
Are you expecting an output record with `PollingHealth` and `PollingStatus` reflecting the failure?

It looks like an error is being recorded, but not a failure (https://github.com/kentik/ktranslate/blob/main/pkg/inputs/snmp/metrics/device_metrics.go#L97) and those fields are driven by the current value of the failure gauge.
