### ISSUE TITLE
potential overflow of netflow messages length

### ISSUE THREAD

**Issue by pyke369** [kentik/ktranslate#549]
Because Kentik is enriching input flows with additional fields (such as source/destination asnum), and also using an extended template to accomodate v4/v6 addresses, there may be situations where the total raw IPFIX packet size is > 64k (65536 bytes), leading to an invalid (overflowed/rolled-over) lengh value in the packet header, b/c of the cumulative size of the new data flowsets:

- https://github.com/kentik/ktranslate/blob/main/pkg/formats/netflow/ipfix.go#L50
``` 
48     header := ipfix.MessageHeader{
49         Version: f.version,
50         Length:  uint16(dataBuf.Len() + 16), // Payload + msgheader length  <------ here
51     }
```

- when using the `file` sink of the `net` sink in tcp mode, it produces invalid output from time to time (which can be circumvented by trying to read an extra 64k chunk of data and add it to the previous chunk when the next IPFIX message header seems "unsynchronized", a poor-man solution though).

- when using the `net` sink in udp mode, it yields some "Message is too large" errors (a udp datagram payload is also imited to 65536 bytes, the length being encoded as an uint16), leading to flows loss (the udp.Write() call just fails).

I don't have a mitigation code at this point, but I could provide one if needed (the packer should be amended to generate multiple concatenated IPFIX messages, and the net/udp sink should loop to send a >64k buffer in multiple parts).

**Comment by i3149** [comment]
Great find! if you can contribute a PR this would be awesome!

**Comment by pyke369** [comment]
I'll give it a try.

**Comment by i3149** [comment]
That's a great idea to add in all the info there is into the exported flow. This data should be present in each flow record sent to the `Format` function:

```
flows[0].CompanyId, flows[0].DeviceName, flows[0].DeviceId
```

**Comment by pyke369** [comment]
I had a deeper look a the code and found there's already some way to limit the number of exported flow per batch/message, by simply setting the `maxflowspermessage` configuration entry (default 10000, which is way too high in the netflow case). The current netflow template yields 120 bytes data flowsets, and if you add the template flowset itself (92 bytes) and the netflow header (16 bytes), the maximum flows per exported message should be:

```
int((65535 - 16 - 92) / 120) = 545
```
So let's say `512` for a safe margin.

**Comment by pyke369** [comment]
I contributed this PR for you to review: https://github.com/kentik/ktranslate/pull/553.
Thanks.

**Comment by i3149** [comment]
LGMT -- merged in, thanks for the deep dive!
