### ISSUE TITLE
Attempting to poll certain OIDs return log message `<OID> failed to return results` - tcpdump to PCAP shows "Fragmented IP protocol"

### ISSUE THREAD

**Issue by ASchneider-GitHub** [kentik/ktranslate#554]
The profile `elemental/elemental-device.yml` in the `kentik/snmp-profiles` GitHub repository has the following OIDs:
```
  - MIB: ELEMENTAL-LIVE-MIB
    table:
      OID: 1.3.6.1.4.1.37086.5.1.1
      name: eventTable
    symbols:
      - name: eventRunning
        OID: 1.3.6.1.4.1.37086.5.1.1.1.3
        enum:
          notRunning: 0
          running: 1
      - name: eventError
        OID: 1.3.6.1.4.1.37086.5.1.1.1.4
        enum:
          noError: 0
          error: 1
    metric_tags:
      - column:
          OID: 1.3.6.1.4.1.37086.5.1.1.1.2
          name: eventName
      # The numerical ID of the node that the event is running on.
      - column:
          OID: 1.3.6.1.4.1.37086.5.1.1.1.6
          name: nodeId
```
([source](https://github.com/kentik/snmp-profiles/blob/main/profiles/kentik_snmp/elemental/elemental-device.yml#L48-L70))

When Ktranslate attempts to poll those OIDs, the following message is shown in the container's logs:
```
{"log":"2023-03-11T16:00:06.299 ktranslate/neteng_elemental2 [Warn] KTranslate\u003elonelemental02 OID 1.3.6.1.4.1.37086.5.1.1.1.6 failed to return results, Metric Name: nodeId\n","stream":"stdout","time":"2023-03-11T16:00:06.299316892Z"}
```

The OID and Metric Name change depending on the OID being used, but data is never returned from these. In the process of debugging the issue, we grabbed a PCAP file using tcpdump and found what we assume is the source of the issue. Any time an OID from that profile list is polled, the returned packets are fragmented:

```
Fragmented IP protocol (proto=UDP 17, off=0, ID=8c63)
```

The ID changes depending on the packet, but the message stays the same. PCAP can be provided if needed, but will need to be done so privately in case it contains private information. Polling the device directly works and the data is returned correctly. Attempting to switch the SNMP version being used via the config file from v2c to v1 doesn't change anything. 

[fragmentedPacketResources.zip](https://github.com/kentik/ktranslate/files/11163470/fragmentedPacketResources.zip)

**Comment by Mesverrum** [comment]
Sending over the walk now

**Comment by i3149** [comment]
This is related to https://pysnmp.readthedocs.io/en/latest/faq/oids-not-increasing.html. So a poll of `.1.3.6.1.4.1.37086.5.1.1.1.3` will fail, even in snmpwalk, but the top level oid of `.1.3.6.1.4.1.37086.5.1.1.1` will work for this whole mib. Will look at re-working polling to add an option to poll a whole mib all at once and then parse the results out as they come in.
