### ISSUE TITLE
Feat: Not curently collecting the real-time sysName

### ISSUE THREAD

**Issue by Mesverrum** [kentik/ktranslate#556]
Recently realized that for cases where a polled device is a member of a stack/pool/ha cluster/etc if you poll a virtual IP that is shared across multiple hostnames then the recurring discovery will keep adding entries to the base file for each combination of hostname__ip, but when it comes time to do polling we really are just polling the same IP multiple times and decorating it with the device_name that is saved in the base file, not with the current sysName that the device has.  

I think its fine to just generally discourage people from including VIP's in discovery jobs, but I think it would be beneficial if we also collected the sysName and sent that in the same way we do sysDesc.  Just to make it easier to identify when hostnames change and so we could use that a kind of indicator to clean up the snmp base file for possible duplication of the same IP.

**Comment by i3149** [comment]
For this use case we recommend polling with snmp v3. Then we use the engine ID to dedupe the same device behind a vip at disco time.

**Comment by i3149** [comment]
But you're thinking to take this line

```
		if dst.DeviceName == "" {
			dst.DeviceName = dd.DeviceMetricsMetadata.SysName
		}
``` 

And use the sysname as the device name each time through? I see that `Sysname` is set for the uptime metric but no other metrics. We can also add `Sysname` to every metric, just like we do `device_name` now. Sysname is polled every 30 min currently along with the rest of the metadata.

**Comment by Mesverrum** [comment]
so i think when i was looking at the data I might not have looked back deep enough to see the 30m sysname data point.  Now that you point this out I think its okay to keep it how it is, ultimately I want to be able to a report that shows me all the times when device_name is not the same as sysname.  Maybe the user has manually set a device_name differently for whatever reason, but we do want to also know when the sysname is changed and the device name is no longer reflecting the reality of the hardware.

**Comment by Mesverrum** [comment]
For your v3 scenario, does every member of a switch stack report the same engineid when they change the master?  I'm trying to understand what I'd find in the devices list in a v3 scenario.

**Comment by i3149** [comment]
> so i think when i was looking at the data I might not have looked back deep enough to see the 30m sysname data point. Now that you point this out I think its okay to keep it how it is, ultimately I want to be able to build a report that shows me all the times when device_name is not the same as sysname. Maybe the user has manually set a device_name differently for whatever reason, but we do want to also know when the sysname is changed and the device name is no longer reflecting the reality of the hardware.

OK, cool. Easy enough to jiggle around if you think of a reason to down the road. 

> For your v3 scenario, does every member of a switch stack report the same engineid when they change the master? I'm trying to understand what I'd find in the devices list in a v3 scenario.

The code is: 

```
	// Remove any duplicate devices based on Engine ID here.
	for dip, d := range conf.Devices {
		if !conf.Disco.NoDedup && d.EngineID != "" {
			if _, ok := byEngineID[d.EngineID]; ok {
				// Someone else has this engine ID. Delete this device.
				log.Warnf("Removing device %s because of duplicate EngineID %s.", d.DeviceName, d.EngineID)
				delete(conf.Devices, dip)
				stats.added--
			} else {
				byEngineID[d.EngineID] = d
			}
		}
	}
```

Basically there's the `engine_id: ee:00:1f:a1:80:9b:80:bd:0e:dc:b9:c6:63:00:00:00:00` field in the device list and by default this will be unique -- only 1 device can have a common id. Good question on this and a switch stack. Probobly only 1 device but with a kinda random device name being the first switch found?

**Comment by i3149** [comment]
> so i think when i was looking at the data I might not have looked back deep enough to see the 30m sysname data point. Now that you point this out I think its okay to keep it how it is, ultimately I want to be able to build a report that shows me all the times when device_name is not the same as sysname. Maybe the user has manually set a device_name differently for whatever reason, but we do want to also know when the sysname is changed and the device name is no longer reflecting the reality of the hardware.

OK, cool. Easy enough to jiggle around if you think of a reason to down the road. 

> For your v3 scenario, does every member of a switch stack report the same engineid when they change the master? I'm trying to understand what I'd find in the devices list in a v3 scenario.

The code is: 

```
	// Remove any duplicate devices based on Engine ID here.
	for dip, d := range conf.Devices {
		if !conf.Disco.NoDedup && d.EngineID != "" {
			if _, ok := byEngineID[d.EngineID]; ok {
				// Someone else has this engine ID. Delete this device.
				log.Warnf("Removing device %s because of duplicate EngineID %s.", d.DeviceName, d.EngineID)
				delete(conf.Devices, dip)
				stats.added--
			} else {
				byEngineID[d.EngineID] = d
			}
		}
	}
```

Basically there's the `engine_id: ee:00:1f:a1:80:9b:80:bd:0e:dc:b9:c6:63:00:00:00:00` field in the device list and by default this will be unique -- only 1 device can have a common id. Good question on this and a switch stack. Probobly only 1 device but with a kinda random device name being the first switch found?
