### ISSUE TITLE
Bug: Kentik ICMP metrics missing dynamic tags

### ISSUE THREAD

**Issue by araddas** [kentik/ktranslate#567]
We are using dynamic tags to populate a contact record tag which is working for SNMP metrics, however, for ICMP metrics the "$SysContact" is not being dynamically set and instead is returning $SysContact. The ICMP metrics should inherit the dynamic tags that are set at the global or device level```user_tags```.

SNMP Metric Tag Example
```
kentik.snmp.CPU: contact.record => yourfriendlynetworkengineers@companyabc.com
```

ICMP Metric Tag Example
```
kentik.ping.PacketLossPct: contact.record => $SysContact
```

**Comment by i3149** [comment]
Any chance you have the `ping_only` option turned on for this device? I'm not able to replicate this behavior myself  except for devices where `ping_only` is true. Since these arn't getting snmp polled it would make sense that the dynamic tags can't get updated here.

**Comment by araddas** [comment]
@i3149 thats definitely not the case, I have attached a csv export showing the missing dynamic tags, to be honest the behavior seems random on which metric gets the dynamic tag and which one doesn't.

**Respective NRQL Query**
```
FROM Metric SELECT metricName, instrumentation.name, SysContact where device_name = 'devicemissingtags.local' and metricName like '%ping%' since 15 minutes ago limit 200
```
[kentik_ping_missing_tags.csv](https://github.com/kentik/ktranslate/files/11434690/kentik_ping_missing_tags.csv)

**Comment by i3149** [comment]
Thanks! I'll look more here.

**Comment by i3149** [comment]
Re-opening because of a new report in #591

**Comment by dconnolly-sfdc** [comment]
commenting to keep open
fyi @araddas 
@i3149 any update or further info required

**Comment by kru-sfdc** [comment]
@i3149 Any update pls.

**Comment by i3149** [comment]
Keeping open to look further.
