### ISSUE TITLE
💡 FR - Add new conversion `CPUIdleMil`

### ISSUE THREAD

**Issue by thezackm** [kentik/ktranslate#615]
[ref code snippet](https://github.com/kentik/ktranslate/blob/d059b3cbe838ea7e37771517ae9d7cfba31dcf07/pkg/inputs/snmp/metrics/device_metrics.go#L281-L285)

```go
        // If CPUIdle is present, calculate CPU from this.
        if cpui, ok := dst.CustomBigInt["CPUIdle"]; ok && cpui <= 100 {
            dst.CustomBigInt["CPU"] = 100 - cpui
            dst.CustomMetrics["CPU"] = dst.CustomMetrics["CPU"]
        }
```

In the `ISILON-MIB`, [clusterCPUIdlePct](https://circitor.fr/Mibs/Html/I/ISILON-MIB.php#clusterCPUIdlePct) is defined as:

> Average amount of idle CPU time (per mil) averaged for all nodes averaged for all nodes over the last 5 seconds.

With results like this: 

```
.1.3.6.1.4.1.12124.1.2.3.5.0 = Gauge32: 902
```

---

We need a new conversion tag that applies the right math in this situation. 

Suggestion: `CPUIdleMil`

```go
        // If CPUIdleMil is present, calculate CPU from this.
        if cpuim, ok := dst.CustomBigInt["CPUIdleMil"]; ok && cpuim <= 1000 {
            dst.CustomBigInt["CPU"] = (1000 - cpuim)*0.1
            dst.CustomMetrics["CPU"] = dst.CustomMetrics["CPU"]
        }
```

In this example, the result should be `CPU = 9.8`

**Comment by i3149** [comment]
What do you think about my idea to use Python for this because there's only 1 profile which can use this logic? 

https://github.com/kentik/snmp-profiles/pull/709
