### ISSUE TITLE
Kentik synthetics output to OTLP format

### ISSUE THREAD

**Issue by jryburn** [kentik/ktranslate#628]
Our friends over at SumoLogic would love to see us output OTLP formatted data from ktranslate instead of the JSON they are using today. Initially they are interested in putting Kentik synthetics into this format but flow data could be interesting too if the output format supports both.

https://opentelemetry.io/docs/specs/otlp/

**Comment by dpajin-kentik** [comment]
I don't know all the details about OTLP, but as you said, it is similar to Prometheus on the metrics side. Unfortunately, it is probably not the same. OTLP supports 3 types of data, Metrics, Logs and Traces. I am not sure what would be the best way to transport flow, we should think about this in more details

**Comment by jryburn** [comment]
I've only scanned the OTLP docs but they do have some example GoLang code if that helps. I'm not sure if Metrics or logs would make more sense of our data but keep in mind it would be flow, cloud, and syn we would want to be able to transport ultimately. Sumo cares mostly about syn as that is the current integration we have.

**Comment by jryburn** [comment]
@i3149 is working on an OTEL exporter of Kentik data. We are currently working with Sumo to attempt to get them to sponsor us to be part of the OpenTelemetry project within the CNCF. Some politics we are working through.
