### ISSUE TITLE
Kentik synthetics metrics: expose as gauge, not as counter

### ISSUE THREAD

**Issue by dpajin-kentik** [kentik/ktranslate#629]
I think that all metrics which are exposed by Ksynth should be exposed as Gauge (as that is the nature of those metrics), while ktranslate is exposing them as Counters. This makes an issue, since the metrics such as "packets sent" or "packets loss" are increasing over time and the output really acts like a counter.

**Comment by i3149** [comment]
I think this is good in my testing now. LMK when you can have a chance to validate.

**Comment by i3149** [comment]
Working now.
