### ISSUE TITLE
Bug: s3Sink Cannot upload to s3: RequestError: send request failed

### ISSUE THREAD

**Issue by Let-itGo** [kentik/ktranslate#635]
Issue: 
caused by: Post "https://_<s3_bucket_path_with_filename>_.gz?uploads=": dial tcp: lookup _<s3_bucket_name>_._<s3_endpoint>_ on `<IP>`: read udp _<IP_A>_:_<Port_A>_->_<IP>_:53: i/o timeout
2023-11-28T13:01:41.140 ktranslate/ [Error] s3Sink Cannot upload to s3: RequestError: send request failed

I was checking online for this issue but found this comment from CpuId "https://github.com/hashicorp/terraform/issues/10354#issuecomment-263026960"

**Comment by i3149** [comment]
Port `53` and `udp` here is saying its a dns issue. Best guess is that your dns server is slow so hence the i/o timeout. If running in docker, can you set the `--dns` flag to your preferred dns provider. For example, `--dns=1.1.1.1` to use Cloudflare.
