### ISSUE TITLE
Add build arg for external snmp-base.yaml

### ISSUE THREAD

**Issue by michael-staffa** [kentik/ktranslate#638]
I'm maybe missing something, but I don't see an option for copying a local `snmp-base.yaml` file in the Dockerfile.

I'm building the image for Kubernetes (not running locally in Docker) and want to be able to package my config with it during the build process instead of the runtime setting as is done in the [quickstart](https://github.com/kentik/ktranslate/wiki/SNMP-Quickstart#example-output-to-new-relic-sink).

**Comment by i3149** [comment]
Good call out. I can see why you would want to bundle the file into the base image for k8s. But, there's no easy way I can see to conditionally copy a file if it exists in docker. 

Instead, can you drop your version of `snmp-base.yaml` into the `./config` dir? The whole directory is copied over to `/etc/ktranslate` at https://github.com/kentik/ktranslate/blob/main/Dockerfile#L43. 

Then just set the flag `-snmp=/etc/ktranslate/my-snmp-file.yaml` and you should be good to go.

**Comment by michael-staffa** [comment]
I'm happy with that in general. Could do the copy between cloning and building and just set a flag 👍🏻 
I was thinking more just a build arg that feeds into a COPY if the arg is provided, and defaulting to the one in the `./config` if it's not.

**Comment by i3149** [comment]
An arg defaulting to `./config` sounds good to me. I'll add this in.
