### ISSUE TITLE
💡 FR - Add graceful error handling to Meraki API requests

### ISSUE THREAD

**Issue by thezackm** [kentik/ktranslate#639]
_similar to PR #637_

There are breaking errors that occur when the Meraki API integration hits 400 errors. For example, attempts to monitor VPN status in a Meraki organization that has no VPNs shows an error like this in the container logs:

```
2023-12-06T15:54:31.696 ktranslate/meraki [Info] KTranslate>meraki Meraki cannot get vpn status Info: [GET /organizations/{organizationId}/appliance/vpn/statuses] getOrganizationApplianceVpnStatuses (status 400): {}
```

When the error is generated, it seems to kill the rest of the scheduled polling and nothing is sent to the target sink.

---

_As a user, I need ktranslate to log API polling errors but still attempt the rest of the configured polling and send results to the target sink._

**Comment by i3149** [comment]
Closed with #641
