### ISSUE TITLE
FR: Calculation of IfInUtilization and IfOutUtilization using items collected by SNMP MIB-2 Interfaces

### ISSUE THREAD

**Issue by MarthaSJP** [kentik/ktranslate#643]
The current IfInUtilization and IfOutUtilization calculations are based on ifHighSpeed (Mbps), which can be obtained from OID 1.3.6.1.2.1.31.1.1.15.

https://github.com/kentik/ktranslate/blob/e5c428c4c4e7949a9d0371de2ffcfa077c461dd6/pkg/formats/nrm/nrm.go#L621-L635

There are cases where iHighSpeed is not supported for older devices or slower interfaces and therefore cannot be calculated.
Could you please consider making it possible to calculate IfInUtilization and IfOutUtilization using items that can be obtained from SNMP MIB-2 Interfaces?

Thank you.

**Comment by i3149** [comment]
Seems reasonable, I'll see what I can do.

**Comment by i3149** [comment]
@MarthaSJP Can you pull the `kentik/ktranslate:staging` docker image and try it out. This image I think should work for your use case but its hard for me to test. Thanks!

**Comment by MarthaSJP** [comment]
@i3149 Thanks for responding! I will check it in my environment. I am using New Relic, so is it ok to check the calculation results on the New Relic UI?

I will check it in the first half of next week as I can't take the time this week.

**Comment by i3149** [comment]
Sure, NR is a fine place to check. No rush!

**Comment by MarthaSJP** [comment]
@i3149 I just had time to check it out.
SNMP configuration was performed on the same router in the latest container image and in the staging container image to verify the new program operation.

The modified program was getting the ifSpeed values obtained by snmpwalk and was also calculating interface utilization.

![スクリーンショット 2024-01-12 22 46 49](https://github.com/kentik/ktranslate/assets/112815247/6acd29bf-5e43-4170-a197-bac89b1826c5)

<img width="444" alt="image" src="https://github.com/kentik/ktranslate/assets/112815247/c277d5b7-cca3-4fe8-b13d-78fc8b68650a">

In the program before the modification, ifSpeed was all 0.

<img width="327" alt="image" src="https://github.com/kentik/ktranslate/assets/112815247/37093817-d178-4030-a95d-c6856e43e297">

I would like to confirm one thing. Is my understanding correct that the ifSpeed used in the calculation is not using the value set in the profile (IF-MIB), but is using the value obtained based on a hard-coded definition within ktranslate?
I am concerned about the impact on the environment in which we are currently operating, so I checked.

**Comment by i3149** [comment]
@MarthaSJP, thanks for evaluating. Those utilization numbers look a bit low to me unless you think they are accurate? I'm trying to make the utilization calc work for both ifSpeed in bits/sec and ifHSpeed in mbit/sec and likely got some math wrong. 

The mibs used are hard coded, with both 

```
		m.Set("1.3.6.1.2.1.31.1.1.1.15", SNMP_ifHSpeed)      // Index ifIndex
		m.Set("1.3.6.1.2.1.2.2.1.5", SNMP_ifSpeed)           // Index ifIndex
```

Being polled. Will this work for you?

**Comment by MarthaSJP** [comment]
@i3149, the usage is low because I checked it with the verification router I have on hand and it does not have a lot of traffic.
I recalculated using ifHCInOctets, if_Speed and data acquisition interval and got the same result. I believe there is no problem with the logic of the calculation.

( (ifHCInOctets * 8) / (60sec * if_Speed)) * 100

Polling defined in hard code is also working fine.
I have removed the ifSpeed MIB definition from the profile and still get ifSpeed.

**Comment by i3149** [comment]
Cool, sounds like things are working then. I'd like to not change the mbits -> bits for existing users though so let me push one more change up which will keep results the same for folks using `SNMP_ifHSpeed`.

**Comment by MarthaSJP** [comment]
Hi @i3149, this update was committed but has now been reverted.https://github.com/kentik/ktranslate/pull/664

Do you know the cause of the bug as it occurred? Please let me know if this needs to be verified as I would really like to implement this feature.
I will help you as much as I can.

Thank you.
