### ISSUE TITLE
FR: Support for retrieving secrets from Azure Key Vault

### ISSUE THREAD

**Issue by PolovicJ** [kentik/ktranslate#649]
Organizations, that are unable to leverage on AWS Secrets Manager, are left with no option but to store their SNMPv3 credentials in configuration file as plain text.

Could you please consider extending secrets management feature to have ktranslate pull in credentials from Azure Key Vault during Docker runtime?

Multi-line secrets are supported in Azure Key Vault as well so the secrets could be stored in JSON format with all the relevant key:value pairs (similar to AWS).

```
{
  "user_name": "$YOUR_USER_NAME",
  "authentication_protocol": "$YOUR_AUTHENTICATION_PROTOCOL",
  "authentication_passphrase": "$YOUR_AUTHENTICATION_PASSPHRASE",
  "privacy_protocol": "$YOUR_PRIVACY_PROTOCOL",
  "privacy_passphrase": "$YOUR_PRIVACY_PASSPHRASE"
}

```

**Comment by i3149** [comment]
This feature is already supported! https://github.com/kentik/ktranslate/blob/main/pkg/kt/snmp.go#L576

Use something like 

```
default_v3: azure.kv.my-key-name
```

And set this environment var: `KT_AZURE_KEY_VAULT_URL` with something like `https://my-vault-name.vault.azure.net/` 

This will replace the v3 auth just like in AWS word with the value of yaml in the key `my-key-name` of the value in the env var. 

There's also Google Secret Manager support where you use the prefix `gcp.sm.` 

I'll work with the NR side to get this documented as I think Azure and GCP slipped through the cracks.

**Comment by PolovicJ** [comment]
First of all, thank you for reviewing this issue and sorry for my late response!

I played with this feature, however without a solid documentation it was not so easy to implement.

After finding more clues in the code I believe more [environment variables](https://github.com/Azure/azure-sdk-for-go/tree/main/sdk/azidentity#environment-variables) have to be set when deploying a container. Azure credentials have to be passed to Azure Identity SDK so that application can access the key vault.

Do you have any advice on using multiple SNMPv3 credentials together with Azure Key Vault?
Is it possible to retrieve multiple secrets within one `snmp_base.yaml` file or do we need to pass one JSON block containing all secrets into `other_v3s` key?

**Comment by i3149** [comment]
Thanks for poking around! I think we're working to document now. You are correct, those env vars should be what you need. 

For multiple snmpv3 creds, I'd probobly use the `other_v3s` section. For example, 

```
    other_v3s:
        - azure.kv.my-key-name-one
        - azure.kv.my-key-name-two
        - azure.kv.my-key-name-three
```

you can let the `default_v3:` be null here and these other ones will be tried in order. Hope this helps!

**Comment by PolovicJ** [comment]
Thank you, Ian! This will definitely help us passing multiple secrets into multiple SNMPv3 creds.

However, we're still struggling with retrieving secret's value:

```
2024/02/12 08:35:56 failed to get azure secret: Get "https://KVNAME.vault.azure.net/secrets/ktranslate-snmpv3/?api-version=7.3": EOF
2024-02-12T08:35:56.572 ktranslate/akv-test [Error] KTranslate There was an error when polling for SNMP devices: yaml: mapping values are not allowed in this context.
```

It looks like figured the authentication and client creation out, but we can't get the secret from Key Vault using 
[azureClient.GetSecret](https://github.com/kentik/ktranslate/blob/0638a8b7ef385f5c480dfbd146f302ac2dd3d54e/pkg/kt/azure.go#L56) function. Is there any way to troubleshoot the underlying [Azure Identity SDK](https://github.com/Azure/azure-sdk-for-go/blob/b6c374e4059cd84ba20c06041db28dde39963227/sdk/security/keyvault/azsecrets/client.go#L200) within ktranslate container?

I believe it's not related to permission, as we managed to get the same secret from key vault using same URI and service principal via Azure CLI.
