### ISSUE TITLE
Add logging for IP lookup error 

### ISSUE THREAD

**Issue by nijugeorge173** [kentik/ktranslate#660]
Please add logger for IP lookup errors at this [line](https://github.com/kentik/ktranslate/blob/e9135f1c17c03e7b5276bed57b513eb981f2249e/pkg/util/resolv/resolver.go#L94)

**Comment by i3149** [comment]
Does this work for you?

**Comment by nijugeorge173** [comment]
Yes looks good and the 'log' flag is set to true always as I understand. We are trying to debug an IP resolution issue which is not evident from other tests.
