### ISSUE TITLE
Prometheus: rollups out_bytes and out_pkts not possible

### ISSUE THREAD

**Issue by nfranchet** [kentik/ktranslate#68]
I try to do rollups for out_bytes and out_pkts but it does not work.

This is my command line:
`KTranslate CLI: [ktranslate -metalisten 0.0.0.0:8083 -listen 0.0.0.0:8082 -mapping /etc/ktranslate/config.json -geo /etc/ktranslate/GeoLite2-Country.mmdb -udrs /etc/ktranslate/udr.csv -api_devices /etc/ktranslate/devices.json -asn /etc/ktranslate/GeoLite2-ASN.mmdb -log_level info -format prometheus -kentik_email <my_email> -format_rollup prometheus -sinks prometheus -prom_listen=:8084 -rollup_interval 60 -rollups sum,in_pkts,in_pkts,device_name -rollups sum,out_pkts,out_pkts,device_name]`

in the prometheus exported file I have only 
```
# HELP in_pkts
# TYPE in_pkts counter
in_pkts{device_name="core03_pa4_par"} 405

```

But no out_pkts.
I try with in_bytes/out_bytes and only in_bytes is exported :(

Is there a mistake in my command line ?

**Comment by i3149** [comment]
How are you sending data in? If the sum of a rollup is 0 it isn't exported here. 

The CLI itself looks good.

**Comment by nfranchet** [comment]
The data come from Firehose. But I check the out_bytes and out_pkts and you are right, the sum is 0 :(
I have to check with another device :)

**Comment by i3149** [comment]
Sounds good. Only other thing is if you want to adjust for sample rate in the rollups, use a `s_` prefix for the operator. For example:

`-rollups s_sum,in_pkts,in_pkts,device_name`
