### ISSUE TITLE
Support podman containers

### ISSUE THREAD

**Issue by sskilbred** [kentik/ktranslate#690]
In secured environments, Docker will typically not comply to the security requirements - specifically the fact that root access is needed. Podman solves this problem for many companies. Considering that Podman is very similar to Docker, the requests would be to formally start supporting Podman containers to run kTranslate.

**Comment by i3149** [comment]
You should just be able to do `podman pull docker.io/kentik/ktranslate:v2`. There's no difference under the hood between a docker image and a podman one afaik.

**Comment by sskilbred** [comment]
It would be great if this is something that could be mentioned in the Wiki as well :)

**Comment by i3149** [comment]
That's fair, I'll add.
