### ISSUE TITLE
REAL is forbidden

### ISSUE THREAD

**Issue by cyclone21** [kentik/ktranslate#701]
I am trying to use mibdump.py to convert the HP-LASERJET-COMMON-MIB from  https://www.circitor.fr/Mibs/Html/H/HP-LASERJET-COMMON-MIB.php and I am getting:
```
Failed MIBs: HP-LASERJET-COMMON-MIB (REAL is forbidden at MIB HP-LASERJET-COMMON-MIB, line 9888)
``` 

In the MIB file it has:
```
usage-printer-total-charge OBJECT-TYPE
    SYNTAX  REAL
    ACCESS  read-only
    STATUS  optional
    DESCRIPTION
                "Total printer charge for all paper sizes printed."
::= { printer-accounting 2 }

``` 

I am guessing the script maybe doesn't support the REAL data type?

**Comment by i3149** [comment]
`mibdump.py` is not a part of ktranslate. Its maintained over here: https://github.com/etingof/pysmi/tree/master and we can't provide support for it. 

This said, if you are trying to monitor HP printers, its probably best to hand roll a short yaml config which gets you started with just a few oids to monitor.   You'll need the sysOID for the device which you can get from snmpwalk and then add one metric like 1.3.6.1.2.1.43.9.2.1.1 (prtOutputIndex): output capacity (0 or more; 0 means out of paper), copying from https://iphostmonitor.com/monitoring-toner-level-in-snmp-capable-hp-printer.html.
