### ISSUE TITLE
Request to Revisit Issue #643 on IfUtilization Calculations

### ISSUE THREAD

**Issue by MarthaSJP** [kentik/ktranslate#710]
Dear ktranslate Team,

I'm following up on Issue #643 regarding the IfInUtilization and IfOutUtilization calculations. As older devices and slower interfaces don't support ifHighSpeed, could we consider alternative calculations using SNMP MIB-2 Interfaces?

Although PR #645 addressed this, it was reverted in PR #664 and the issue remains unresolved. I'm keen to assist in any way to help resolve this, possibly by exploring different solutions together.

Thank you for considering this request. I look forward to your feedback.

Best regards,

**Comment by khara-NewRelic** [comment]
Hi ktranslate team, my customer heavily using your solution has faced to the issue and been looking forward to the release including the fix for the issue.
Thanks!!!

**Comment by i3149** [comment]
Sorry, I had a regression with this and then I could never find the actual bug! Time permitting I'll circle around and they again.
