### ISSUE TITLE
Best Practices for Container Deployments

### ISSUE THREAD

**Issue by wildcardlinux** [kentik/ktranslate#719]
I have ran into an issue where monitoring 350 routers on 1 container results in sometimes getting null values returned for link names. Increasing the timeout value has helped but the issue persist. Specifically concerning is when the Link State has a value of 'initial' and the Link Name has a value of Null.

Is there any best practices based on any known limitations with the container?

- Should we separate out device types to reduce load on the container?  For example isolating each container to monitor only routers, access points, and switches for example?
- What is the appropriate way to declare cidr ip ranges? Because the discovery takes so long to complete the cidr range, the container gets hung up and doesn't discover devices later in the range. What is the best way to manage cidr declaration in the container configuration to not have to specifically use a long list of /32 addresses.
- Is monitoring about 1000 access points per each container going to be a problem?

If you could help with answering these questions that would be extremely helpful. This is the link to the kentik profile if you need it:

- https://github.com/kentik/snmp-profiles/tree/main/profiles/kentik_snmp/velocloud

**Comment by i3149** [comment]
All great q's. As usual, the answer is "it depends". 

> * Should we separate out device types to reduce load on the container?  For example isolating each container to monitor only routers, access points, and switches for example?

Its not so much the type of device as number of devices which can cause load. Ideally you will keep around say 100 devices per container instance. 

> * What is the appropriate way to declare cidr ip ranges? Because the discovery takes so long to complete the cidr range, the container gets hung up and doesn't discover devices later in the range. What is the best way to manage cidr declaration in the container configuration to not have to specifically use a long list of /32 addresses.

How big of a space are you talking about? And how dynamic is the environment? Is it feasible to list some `/24s` and call it a day?

> * Is monitoring about 1000 access points per each container going to be a problem?

Ideally you'll have 10 instances monitoring these 1000 aps. Reducing latency is also the key to scaling. Can you locate the ktranslate containers close-ish to the buildings where the APs are?

**Comment by i3149** [comment]
Gonna close this but feel free to re-open if you still need feedback.

**Comment by RFXTECH** [comment]
Thank you, we are trying to monitor about 6400 devices and they are static ip'ed so after the discovery we could remove the ranges if that would help.  Is it a requirement that the container be on the LAN with devices?   We are trying to monitor them over sd-wan connections with avg 30msec latency, how big of an issue could that be?  Is there a way to know if that is causing the NULL value issues?

**Comment by wildcardlinux** [comment]
Wanted to reopen:

Thank you, we are trying to monitor about 6400 devices and they are static ip'ed so after the discovery we could remove the ranges if that would help. Is it a requirement that the container be on the LAN with devices? We are trying to monitor them over sd-wan connections with avg 30msec latency, how big of an issue could that be? Is there a way to know if that is causing the NULL value issues?

**Comment by jryburn** [comment]
Looks like the outstanding question was answered in https://github.com/kentik/ktranslate/issues/729
