### ISSUE TITLE
Missing Otel metrics?

### ISSUE THREAD

**Issue by i3149** [kentik/ktranslate#722]
Hi,
I'm evaluating the otel metrics but seeing some (14) metrics missing compared to when the same yaml is used to send to new relic
any advice if this is expected behaviour or a bug that could be fixed ?

config A - sending to New Relic
docker run -d \
  --name ktranslate-test-nonprod \
  --restart unless-stopped \
  --user id -u:id -g \
  -v pwd/otel_test.yaml:/snmp-base.yaml \
  -e NEW_RELIC_API_KEY=$YOUR_NEW_RELIC_API_KEY \
  -e AWS_ACCESS_KEY_ID=$YOUR_AWS_ACCESS_KEY_ID \
  -e AWS_SECRET_ACCESS_KEY=$YOUR_AWS_SECRET_ACCESS_KEY \
  -e AWS_REGION=us-west-2 \
  -e KENTIK_PING_PRIV=true \
  -d kentik/ktranslate:v2 \
  -snmp /snmp-base.yaml \
  -service_name=snmp \
  -log_level=info \
  -tee_logs=true \
  -metrics=jchf \
  -nr_region=US \
  -nr_account_id=2395010 \
  nr1.snmp

config B - exporting to OTEL Collector
docker run -d \
  --name ktranslate-otel-export \
  --restart unless-stopped \
  --user id -u:id -g \
  -v pwd/otel_test.yaml:/snmp-base.yaml \
  -e AWS_ACCESS_KEY_ID=$YOUR_AWS_ACCESS_KEY_ID \
  -e AWS_SECRET_ACCESS_KEY=$YOUR_AWS_SECRET_ACCESS_KEY \
  -e AWS_REGION=us-west-2 \
  -e KENTIK_PING_PRIV=true \
  -p 4317:4317 \
  -p 4318:4318 \
  -d kentik/ktranslate:v2 \
  -format=otel \
  -otel.protocol=grpc \
  -otel.endpoint=http://10.46.82.243:4317/ \
  -snmp /snmp-base.yaml \
  -log_level=debug \
  -tee_logs=true \
  -metrics=jchf

config
otel_test.yaml is here 
https://gist.github.com/dconnolly-sfdc/d497918b322a450bbf19715e8f63d3bb
Gist
[otel_test.yaml](https://gist.github.com/dconnolly-sfdc/d497918b322a450bbf19715e8f63d3bb)
otel_test.yaml. GitHub Gist: instantly share code, notes, and snippets.
otel_test.yaml
Missing metrics are here
kentik.ktranslate.chf.kkc.device_metrics
kentik.ktranslate.chf.kkc.interface_metrics
kentik.ktranslate.chf.kkc.metadata
kentik.ktranslate.chf.kkc.snmp_fail
kentik.ktranslate.chf.kkc.snmp_missing
kentik.ktranslate.chf.kkc.snmp_missing_meta
kentik.ping.AvgRttMs
kentik.ping.MaxRttMs
kentik.ping.MinRttMs
kentik.ping.PacketLossPct
kentik.ping.PacketsRecv
kentik.ping.PacketsSent
kentik.ping.StdDevRtt
kentik.snmp.Uptime
logs
kentik.ktranslate.chf.kkc.device_metrics to be in the format for new relic event api 

docker logs ktranslate-otel-export | grep kentik.ktranslate.chf.kkc.device_metrics
[{"metrics":[{"name":"kentik.ktranslate.chf.kkc.inputq","type":"gauge","value":11.47,"attributes":{"host":"c32a729f247c","ver":"kt-2024-06-18-9567798613","instrumentation.name":"heartbeat","eventType":"KTranslateMetric","type":"meter","device_name":"c32a729f247c","provider":"kentik-agent"}},{"name":"kentik.ktranslate.chf.kkc.inputq_len","type":"gauge","value":0,"attributes":{"instrumentation.name":"heartbeat","force":"true","host":"c32a729f247c","ver":"kt-2024-06-18-9567798613","provider":"kentik-agent","type":"gauge","device_name":"c32a729f247c","eventType":"KTranslateMetric"}}

**Comment by i3149** [comment]
Gonna close this one out because I can't reproduce. To ensure that all internal metrics are exported via otel, be sure to add the flag `-format_metric=otel` .

**Comment by dconnolly-sfdc** [comment]
no need to re-open the issue but just adding an update ...

after adding the option
`-format_metric=otel`

the following metrics are now showing 
`kentik.ktranslate.chf.kkc.device_metrics`
`kentik.ktranslate.chf.kkc.interface_metrics`
`kentik.ktranslate.chf.kkc.metadata`
`kentik.ktranslate.chf.kkc.snmp_fail`
`kentik.ktranslate.chf.kkc.snmp_missing`
`kentik.ktranslate.chf.kkc.snmp_missing_meta`

ping metrics are still missing but i'll continue to troubleshoot
