### ISSUE TITLE
Poller picking up false packet loss on ping_only tests

### ISSUE THREAD

**Issue by briansgill** [kentik/ktranslate#732]
We are using ktranslate agent running as a docker container with NewRelic to do some **ping_only** checks.  We know the version v2.1.23 from Feb2024 is working as expected and returning the expected results.  However any of the recent versions (even v2.1.26 from May2024) are producing intermittent packet loss metrics.  If I had to make a guess it seems v2.1.25 is where something changed related to ping - https://github.com/kentik/ktranslate/releases/tag/v2.1.25 

Based on the NewRelic data collected it appears there were occasionally 6 packets were sent instead of the usual 5. Packets received remains as 5 and its shows as packetLoss.  Let me know if I can provide additional info around this issue.

![OcassionalPacketSent6insteadof5_PacketLossIssue](https://github.com/user-attachments/assets/3cd732d8-4f09-40eb-9d81-525889b718e3)
![NR_NetworkPollerPacketLossIssue](https://github.com/user-attachments/assets/23b3180b-8e60-4923-a34d-dfb61b186ca5)

**Comment by i3149** [comment]
Almost certainly this one: https://github.com/kentik/ktranslate/pull/679/files

I'll look further.

**Comment by i3149** [comment]
I think this should be fixed now, feel free to re-open if you don't see improvement.

**Comment by briansgill** [comment]
Great - just to confirm if I pull "quay.io/kentik/ktranslate:v2" - I will get the updated version that includes the fix mentioned?  Just want to make sure I test with the correct release.  Thanks in advance @i3149
