### ISSUE TITLE
Reopening packet loss on ping_only tests from issue732

### ISSUE THREAD

**Issue by briansgill** [kentik/ktranslate#736]
This is a follow-up to issue 732 - https://github.com/kentik/ktranslate/issues/732 

Pulled version (-- Version kt-2024-08-12-10360414534; Build Mon Aug 12 22:39:38 UTC 2024) to test and did not notice any changes in the results.  Same results were obtained where 6 packets sent and 5 received intermittently.

Pulled version via:
docker pull quay.io/kentik/ktranslate:v2

If the fix is not in the above release please provide the version info that I should be pulling to test.

**Comment by i3149** [comment]
Yar, that's the right version I'll see what I missed.

**Comment by i3149** [comment]
I'm more confident that the just published version should fix this. You may have one loss on the very first or second ping but after that it should be good. Grab this version or later when the CI finishes: 

https://github.com/kentik/ktranslate/actions/runs/10426319864/job/28879032964
