### ISSUE TITLE
Reopening packet loss on ping_only tests from issues 732 and 736

### ISSUE THREAD

**Issue by briansgill** [kentik/ktranslate#738]
This is a follow-up to issues 732 and 736 - https://github.com/kentik/ktranslate/issues/736

There was still packetloss recorded on the initial polling but the bigger issue in the latest version released was some of the devices did not get polled for a lengthly time period as in below example.   The poller was started up at 3pm but it seems this specific host got polled in the beginning and then no more polls on it until like 5:15pm timeframe.  So a >2 hour gap.  There were other hosts having the same type of behavior as well.

![image](https://github.com/user-attachments/assets/71f0c481-1f93-478a-b269-5aad9544618c)

**Comment by i3149** [comment]
Uh oh! Let me try with a new ping engine and see if that's any better.

**Comment by i3149** [comment]
OK, if you're up for it, try one more time and let me know if this one is better. Latest fix building now.

**Comment by briansgill** [comment]
Thanks.  Checking it out now via version kt-2024-08-27-10571748813

**Comment by briansgill** [comment]
@i3149 - looks like the new version is working as expected and not recording any false packet loss.  Old version  was giving pretty static results all the time.  This version seems to be recording variable response times on the pings which probably is more reflective of real world results?  What do you think of the results?

![image](https://github.com/user-attachments/assets/f912db33-9459-4839-8e76-1d827c03c07a)
