### ISSUE TITLE
Allocate jchfs on-demand?

### ISSUE THREAD

**Issue by dhammika** [kentik/ktranslate#74]
Pre-allocation of jchfs takes about 5MB. 
It's not a lot but could add up for synth devices with light flow.

```
      flat  flat%   sum%        cum   cum%   calls calls% + context 	 	 
----------------------------------------------------------+-------------
                                         5123.05kB   100% |   github.com/kentik/ktranslate/pkg/cat.NewKTranslate /home/dhammika/src/github.com/kentik/ktranslate/pkg/cat/kkc.go:84 (inline)
 5123.05kB 81.97% 81.97%  5123.05kB 81.97%                | github.com/kentik/ktranslate/pkg/kt.NewJCHF /home/dhammika/src/github.com/kentik/ktranslate/pkg/kt/types.go:169
```

**Comment by i3149** [comment]
Maybe just a flag to vary the number created?

**Comment by dhammika** [comment]
Suspect noone will actually set it and we'd endup in same place. 
May be keep a counter and add up to chan buffer on demand?

**Comment by i3149** [comment]
Don't really want to add complexity at this time. This would just be for you if you need to reduce memory footprint.
