### ISSUE TITLE
Issue with Meraki API polling

### ISSUE THREAD

**Issue by Rajupln917** [kentik/ktranslate#746]
Hi,

We have Meraki API integration running, intermittently we hit the rate limit (429) where Ktranslate does the retry with a 5secs interval and we start seeing back the data, but once in a while the data totally stops reporting when we check the logs we see bunch of 429 errors followed by below errors where it gets fixed and we see data only after we restart the container.

[Warn] KTranslate>Global-Meraki-Dashboard Uplink Status: Orgname 429, sleeping 5s
**panic: runtime error: invalid memory address or nil pointer dereference**
[Warn] KTranslate>Global-Meraki-Dashboard Device Status: Orgname 429, sleeping 5s
**[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x18ec06c]**

Please check.

Thanks,
Raju

**Comment by i3149** [comment]
Thanks for this report! There should be a stack trace printed out below the error with line numbers. Getting this output will be key to fixing the bug. Can you add it to the issue?

**Comment by Rajupln917** [comment]
No, I don't see any trace with line numbers below this error. It only has another warning log line stating that it is skipping that organisation.

May be it only prints that when it is in debug mode?

**Comment by i3149** [comment]
If I had to guess I think you're only capturing stdout and the stack trace is on stderr. 

One idea I have is to try setting `max_http_retry` in the meraki config and see if this makes a difference in if you get crashes. For example:

```yaml
       meraki_config:
         api_key: "MY_API_KEY"
         max_http_retry: 1
```

Otherwise, if you can poke around and see if its possible to recover the stderr from a container this would be super helpful.

**Comment by Rajupln917** [comment]
`max_http_retry`  is set to 2 by default, do you want me to increase it more?

**Comment by i3149** [comment]
Decrease it -- I was thinking set to 1 or 0. This might make the bug causing the crash not happen.

**Comment by i3149** [comment]
Alternatively, next time it happens can you run `docker logs $NAME_OF_CONTAINER` this should capture both the stdout and stderr with the needed stack trace.

**Comment by i3149** [comment]
>  it doesn't have any stack trace with line numbers.

Weird, I haven't seen this before. 

Anyrate, I added a guard for anything I can think could cause a nil pointer exception into the `kentik/ktranslate:staging` image. Can you pull and run this image and see if the bug goes away? Without a stack trace I can't promise anything so this is all about throwing food on the wall and seeing what sticks.
