### ISSUE TITLE
No metrics or entities shown for meraki integration

### ISSUE THREAD

**Issue by jryburn** [kentik/ktranslate#756]
## **Description**

**Problem Summary:**

***What is the outcome the customer is trying to achieve?:***  
*The customer is trying to configure the meraki integration to monitor their network devices.*  
 [***https://docs.newrelic.com/docs/network-performance-monitoring/setup-performance-monitoring/meraki-api-polling/\#dockerDedicatedContainer***](https://docs.newrelic.com/docs/network-performance-monitoring/setup-performance-monitoring/meraki-api-polling/#dockerDedicatedContainer)

*However after adding the docker container the container starts up properly but we don't see any metrics or entities generated.*  

**Current Status**  
**(Insert a description of the current status and what actions have already been done. Include relevant logs, screenshots, code excerpts, reproduction steps, O/S and product versions, etc):**  
Container originally had no outbound access following the instructions from the docs. Was provided an updated command which worked to connect to the meraki.

* The API key was validated and we can see several networks and resources reported in the logs  
* however no metrics or entities are generated in this account 
* besides the container entity itself

**(awaiting on customer to provide an up-to-date npmdiag, which will include logs)**

**Comment by i3149** [comment]
I'll need the yaml config you're trying to use to get any further. Likely there's some sorta scaling thing going on.

**Comment by i3149** [comment]
Closing this as it was a config mistake.
