### ISSUE TITLE
Firehose Support for Ultimate Exit Dimensions

### ISSUE THREAD

**Issue by kentik-rbarnes** [kentik/ktranslate#759]
Current FH export is limited to peering_edge (inbound from external classified interfaces, outbound from backbone classified interfaces) if we want to report on outbound traffic by Peer/Provider.

Ideal spot to make this measurement for outbound traffic is actually closer to the access layer (ie. subscribers) where traffic density is somewhat lower (vs a multi Tbit backbone link) which provides better sample rate fidelity for customer traffic. For this to work - we'll need to also include UE dimensions as part of firehose export so we can sample closest to customer, but still report on which providers that customer is utilizing.

**Comment by i3149** [comment]
I can't find a public API which exposes these UE dimensions. Can you file a FR with the API team to expose these via the interface API or other way and then I can add. Will put this on ice until then.

**Comment by kentik-rbarnes** [comment]
I found these in a raw dump I grabbed at some point documented (here)[https://docs.google.com/document/d/1fm_7GZ6HN-YQIheImeUmVahmj-E-2fKI12NvuIuCArw/edit?usp=sharing].

```
  "custom_int": {
    "dscp": 0,
    "flow_flags": 0,
    "ult_exit_device_id": 26843,
    "ult_exit_port": 703,
    "ult_exit_connect_type": 25
  },
```
So perhaps it looks like we can export the raw values - but need the API call to look up the mappings to these values, correct? could we obtain this via the Device/Interface APIs

**Comment by i3149** [comment]
Huh, who knew! I didn't ;)

Looking closer at the data, I'm seeing these resolved to strings also: 

```
    "ult_exit_network_bndry": "external",
    "ult_exit_device": "XXX_CUSTOMER_DEVICE_NAME",
    "ult_exit_connect_type": 5,
    "ult_exit_port": 1901,
    "ult_exit_device_id": XXX_CUSOMTER_DEVICE_ID,
    "ult_exit_network_bndry": "external",
```

I can resolve the `ult_exit_port` to the name / alias of the port if needed but I'm wondering what more is needed here.

**Comment by i3149** [comment]
What do you think about https://github.com/kentik/ktranslate/pull/760?

It will add in `ult_exit_port_alias` and `ult_exit_port_description`. Anything else missing?

**Comment by kentik-rbarnes** [comment]
oooh, maybe my example I was working off was BEFORE I reconfigured with api.key to resolve these so that part is good!
![image](https://github.com/user-attachments/assets/2fd22a8e-7d29-4fef-9ac9-e620b99e014b)

Ideal report is going to look like this - as measured from the Internal/Host facing subscriber ports.
![image](https://github.com/user-attachments/assets/2c2cbed3-7bba-4379-8e54-489fd78405ad)

Which I think would require at the very least Ultimate Exit Provider here and maybe ult_exit_site but i'd need to confirm with Charter.
Sadly we don't have a UE CDN field. :)

**Comment by i3149** [comment]
Cool. Added in `ult_device_site` and `ult_exit_port_provider`
