### ISSUE TITLE
snmp_json2yaml not working for Synology MIB

### ISSUE THREAD

**Issue by nedl86** [kentik/ktranslate#76]
I have been trying to generate a yaml file for SYNOLOGY-SYSTEM-MIB (available [here](https://global.download.synology.com/download/Document/Software/DeveloperGuide/Firmware/DSM/All/enu/Synology_MIB_File.zip)) following the instructions in the Wiki.

The JSON file seems to generate fine (see attached [SYNOLOGY-SYSTEM-MIB.json.txt](https://github.com/kentik/ktranslate/files/6891578/SYNOLOGY-SYSTEM-MIB.json.txt) generated using `mibdump.py`) but then the YAML conversion (snmp_json2yaml) results in a near-empty file with _only_ the `sysobjectid` info but no metrics, etc:

```
# Autogenerated by ktranslate from /snmp_out/SYNOLOGY-SYSTEM-MIB.json

sysobjectid:
- 1.3.6.1.4.1.6574
- 1.3.6.1.4.1.6574.1.5
- 1.3.6.1.4.1.6574.1.6
- 1.3.6.1.4.1.6574.1.6.1
- 1.3.6.1.4.1.6574.1.4
- 1.3.6.1.4.1.6574.1.6.2
```

I tried re-running multiple times with no luck (same result), then I tried the example in the Wiki (`ZSCALER-NSS-MIB`) and it worked fine. So I'm scratching my head trying to figure out if there's something about the Synology MIB that's incompatible with the auto-generation process. Any help would be much appreciated!

**Comment by i3149** [comment]
Thanks for this. Turns out non table based mibs got ignored. Added and working now.
