### ISSUE TITLE
OTel support?

### ISSUE THREAD

**Issue by KGOH** [kentik/ktranslate#763]
Does ktranslate support OTel? I don't see any mention of open telemetry in your docs, but in the source code there's format/otel

What's the support status? Is it WIP? What OTel data does it send? From the quick glance looks like metrics and logs

**Comment by araddas** [comment]
SNMP Metrics -> OTEL Metrics support was added here:
https://github.com/kentik/ktranslate/pull/694

SNMP Traps -> OTEL Logs support was added here:
https://github.com/kentik/ktranslate/pull/698
