### ISSUE TITLE
Discovery against a Linux container running snmpd returned kentik-pdu for 1.3.6.1.4.1.8072.3.2.10

### ISSUE THREAD

**Issue by jbiggley** [kentik/ktranslate#78]
Is there a reason for kentik-pdu being flagged during discover for http://oid-info.com/get/1.3.6.1.4.1.8072.3.2.10?

 For context, the docker container can be replicated using

docker run -d --name snmpd1 \
  --privileged \
  -p 161:161/udp \
  -v /:/rootfs:ro \
  -v /etc/localtime:/etc/localtime:ro \
  crazymax/snmpd:latest

**Comment by i3149** [comment]
because we don't have a provider set up for `netSnmpEnumerations` or `netSnmp`. Updated to fall back to the generic profile when base.yml is detected.
