### ISSUE TITLE
Discovery incorrectly deduplicates where device name is the same

### ISSUE THREAD

**Issue by jbiggley** [kentik/ktranslate#84]
In a test environment, a docker container (tandrup/snmpsim) generates a synthetic Cisco 3750 response to the read-string cisco_16_switch

When spawning multiple instances of the container and running a discovery, only a single device is added to the snmp-base.yaml file even though the debug logs indicate 6 devices were detected.

> 2021-08-01T23:41:28.837 ktranslate [Info] KTranslate Checked 256 ips in 3.029278324s
> 2021-08-01T23:41:28.837 ktranslate [Info] KTranslate Adding 0 new snmp devices to the config, 6 replaced from 6
> 2021-08-01T23:41:28.838 ktranslate [Info] ktranslate service.Close() called, now waiting for things to settle

The YAML file is populated with an entry like
>   Profiler3750:
>     device_name: Profiler3750
>     device_ip: 10.10.0.14

By changing both instances of Profiler3750 to Switch14 and re-running the discovery, a new instance of the switch from one of the other containers will be added.

Expectation is that device_ip + device_name would be used to define the uniqueness of a device.

**Comment by nickstinemates** [comment]
Looking into this - looks like we need to check more than device name in https://github.com/kentik/ktranslate/blob/main/pkg/inputs/snmp/disco.go#L210

I'll take a look and provide a proper fix.
