### ISSUE TITLE
Bug: Container User no longer has write access to snmp-base.yaml

### ISSUE THREAD

**Issue by thezackm** [kentik/ktranslate#86]
PR #73 introduced a bug for the SNMP discovery workflow where the container user cannot write to update `snmp-base.yaml` with the results of discovery; giving the following error: 

```
service Run() error: open /snmp-base.yaml: permission denied
```

`chmod 666 snmp-base.yaml` prior to executing discovery has fixed this in testing.

**Comment by nickstinemates** [comment]
Looking into the best way to fix this..

**Comment by i3149** [comment]
Looking at adding 

```
  --user `id -u`:`id -g` \
```
To the snmp discovery command. This is working for me in testing and I've removed the chmod 666 for now.

https://github.com/kentik/ktranslate/wiki/SNMP-Quickstart#step-4
