### ISSUE TITLE
Spaces in filepath of mib_db / mib_profile_dir cause KTranslate to fail

### ISSUE THREAD

**Issue by keeb-dev** [kentik/ktranslate#99]
![image](https://user-images.githubusercontent.com/88590317/128614636-7c8843bd-8bb1-4209-ac98-591be0d41839.png)
![image](https://user-images.githubusercontent.com/88590317/128614637-eeeb35d7-417e-4afd-97ff-d6a9dc9d538f.png)

**Comment by i3149** [comment]
Update to be like this?

```
  mib_profile_dir: c:/"Program Files (x86)"/KTranslate/config/profiles
  mibs_db: c:/"Program Files (x86)"/KTranslate/config/mibs.db
```
